### ISSUE TITLE
Sort Order - Rename Folder case sensitivity issue

### ISSUE THREAD

**Issue by ArtreL** [xivdev/Penumbra#100]
I created folders by adding slashes to the sort order name in the list of installed mods. At first I created the folder with an all-caps name. When I tried to rename it to the same name but Pascal cased it didn't change anything. I then renamed the folder to "Test" and then changed it to the name I tried before and it worked fine.

**Comment by Drakonas** [comment]
I think this is a Windows limitation. Windows' file/folder structure is case insensitive, so if you rename a folder using certain OS commands, but don't change anything but the letter case, it will not update the folder name at all. You'd have to use a different command, but I'm not sure if Dalamud gives access to that.
