### ISSUE TITLE
[Bug] Default Import Mod Color Incorrect

### ISSUE THREAD

**Issue by XArashiX** [xivdev/Penumbra#103]
This is the first of a few bugs I'll post.
I came across this project and want to help where I can. Definitely deleting TexTools and moving over to Penumbra.

When first importing a TexTools modpack from Penumbra 0.4.6.5, on every occurrence;

On the Installed Mods tab,

When a mod is first imported, the text of the mod is highlights as if it is enabled, when by default visually it should be greyed out due to imported mods not automatically being enabled. Only after enabling the mod for the first time and thereafter disabling it does the mod color appear correct while disabled.
![Screenshot 2021-12-31 193946](https://user-images.githubusercontent.com/43384589/147842349-1e446743-70d0-4813-acb3-9f3414d8b3e0.png)

**Comment by Ottermandias** [comment]
Green is not enabled, green is 'newly imported'. You can even filter for that. 

![image](https://user-images.githubusercontent.com/70807659/147848113-5f91d982-65bc-4ac8-a4d7-ead66045f93e.png)
