### ISSUE TITLE
[Feature Request] In-Penumbra Mod Rename

### ISSUE THREAD

**Issue by XArashiX** [xivdev/Penumbra#104]
I think it would be a good idea to incorporate a way to rename mods within Penumbra without renaming the file so that you can group names of mods visually together a lot nicer. Useful for having a large number of mods or mods that have multiple parts or fixes to them.

So that way you don't have occurances like these;

```
Bozjan Helm Hrothgar Fix
Hrothgar & Viera Hats

```
Or stray names like these;
`XaelaM_Default_Arch_demon_horns.ttmp`

And have more of these;
```
_Hrothgar & Viera Hats
Hrothgar & Viera Hats - Bozjan Hrothgar Helm Fix_

Arch Demon Horns
```

**Comment by PrincessRTFM** [comment]
Turn on advanced settings and you can enable edit mode for mod metadata in the mod list to do exactly this.

**Comment by Ottermandias** [comment]
You can set a sort-order path for mods independently from its name, that does not even require advanced settings. Right-click the mod in the list. You can even introduce folders for grouping by inserting forward-slashes.
You should click on the question mark button in the mod selector.
