### ISSUE TITLE
[Feature Request/Issue] Default Collection For Your Character / Animations not working in collection.

### ISSUE THREAD

**Issue by SkylerMews** [xivdev/Penumbra#109]
So, firstly, the collection settings are amazing, I can have mods show on only me and not worry about it affecting NPCs or other people I don't want. 

However, when setting a collection to myself by name, previews, fitting room, and other UI rendered versions of my character are NOT s modded. I know getting this to work on other people isn't really worth-while, but, what if there was a setting to assign a collection to YOUR character only. And that would affect character UI previews and all other types of displays. while leaving everyone else alone?

Secondly, when using a character collection, animation replacements seem to not work. They start the animations for a split-second, before reverting back to normal.

Thank you so much for this mod, truly a gift.

**Comment by Ottermandias** [comment]
Preview and fitting room actors are currently impossible to redraw. Character collections work by redrawing. This can not possibly be done unless we find a better way to set specific collections while drawing specific actors.

Second point is to be expected, animations aren't at all connected with a drawn actor. I probably need to put a huge disclaimer message to character collections further explaining what they can and can not do and how they're a terrible hack.

**Comment by Ottermandias** [comment]
Anything in the default or forced collection gets just replaced on every request to get a file.

A character collection basically works by replacing the default collection for a short moment whenever we KNOW that a specifically named character is drawn in that moment. 
So basically, when a new character appears on your screen and you have auto-redrawing on
- Character gets loaded
- Model requests its files
- Penumbra redirects those requests to modded files
- Character gets drawn with files from default/forced collection
- Penumbra notices that character has Name "X Y" which correspond to a character collection
- Penumbra queues a redraw of that character
- When the redraw queue reaches that character, the character gets undrawn 
- The default collection gets exchanged with the Character Collection
- The character gets redrawn and requests files
- penumbra redirects those requests to modded files from character collection
- character gets drawn with files from character/forced collection
- Default collection gets restored

whenever that character equips a different item it also queues such a redraw, and when you manually redraw any character it will also set the character collection like above, regardless of auto-redrawing.
But any mod where any of these steps won't work will not work with character collections.
And also, this is a hack. If something gets requested from the game during this redraw it might be drawn with the mods from the character collection. Sometimes the file request takes too long and something gets redrawn with half of character and half of default collection etc.

**Comment by SkylerMews** [comment]
Sorry for the late reply! Thank you, that explanation was very detailed! 

Honestly? It's pretty darn amazing with how much has been accomplished so far. Character collections make a lot more sense now! And based on how things work, your character is redrawn the same as others. Even though it's a "hack" I think its pretty clever workaround with the limitations presented.
