### ISSUE TITLE
importing large ttmp file

### ISSUE THREAD

**Issue by AmenneHolelane** [xivdev/Penumbra#11]
hello, i'm trying to import my [hair mod](https://www.nexusmods.com/finalfantasy14/mods/18) but it won't load into the menu. It seems to sit at "importing modpack" for a few minutes but nothing happens after it goes back to the "import textools modpacks" button. is there a max size? textools really doesn't like importing it either lol. the specific ttmp i'm using is [here](https://1drv.ms/u/s!AiKd6vfWxCUJ4je2rTk3qva1GeDn?e=Vib5A3)

**Comment by NotAdam** [comment]
did you build it yourself or using the release?

**Comment by AmenneHolelane** [comment]
Current release
