### ISSUE TITLE
Character collection mods do not load if they are only enabled on a Character Collection.

### ISSUE THREAD

**Issue by Rapsket** [xivdev/Penumbra#111]
Installed mods that are only enabled in a character collection are not enabled at all. 
It appears that the state of "Default" and/or "Forced" are overriding the "enabled" status of any mod in character collections.

Stage: 
- Create a custom collection for a player character
- Install a mod (Eg: https://www.nexusmods.com/finalfantasy14/mods/1087 - v2.4.0 at time of writing, but this is reproducible on every tested mod) 
- Set Default Collection and Forced Collection to either 'None' OR any collection that it is disabled for.
- Enable mod in character collection

Expected Results:
Mod is applied only to Character.

Actual Results: 
Mod is not applied at all.

Workaround:
A) enable the mod in a collection assigned to Default [Forced can remain empty or disabled] 
> Side effect - mod can be enabled AND disabled normally - undermines the point of having a mod that only affects your character.

B) Enable the mod in a collection assigned to Forced
> Side effect - mod cannot be disabled - defeats the purpose of individually configurable mods.

NB: TexTools is "Started Over" and indexes have been reset. 

Aside: I've been trying to figure out what the point of having Forced is. It generally doesn't fill any use case that isn't already satisfied by properly respecting the enabled or disabled state of any mod in any collection. 
IF forced is supposed to represent a mechanism for hierarchical collection inheritance, that should be something configurable in each collection. Because assigning any collection assigned to "Forced" disrespects mod states on collections that may intentionally be disabled.

**Comment by PrincessRTFM** [comment]
Default is not applied when a character collection exists, forced is. If you have a character collection for yourself with mod A, the default collection with mod B, and the forced collection with mod C, then mods A and C will apply to you while mods B and C will apply to everyone else. The forced collection is for mods that you want applied globally, as a "base" set. It's not about inheritance.

**Comment by Rapsket** [comment]
> Default is not applied when a character collection exists, forced is. If you have a character collection for yourself with mod A, the default collection with mod B, and the forced collection with mod C, then mods A and C will apply to you while mods B and C will apply to everyone else. The forced collection is for mods that you want applied globally, as a "base" set. It's not about inheritance.

Explaining how it is supposed to work doesn't address the above issue. Its reproducible.

Again, forced does not fill any use case that enabling or disabling mods in any collection doesn't already cover. If default is enabled, everyone gets it (unless its in a character collection). Enabling a mod in a character collection moots forced anyways. Having forced on violates conditions where a character collection wants a mod disabled. The workaround being not using forced for anything. If it isn't 'meant' to be an inheritance thing, the effect is the same.

**Comment by Ottermandias** [comment]
You enable clothing item A for Default
You enable clothing item B for character XYZ
You enable interface stuff in Forced.

Yes, you can enable interface stuff in Default and every active Character Collection for the same effect and keep enabling it in every new character collection too.
But you can also just set it in Forced and forget about it.
Forced is for the mods that are supposed to be on in any case. It is not required, but it is easier.
What is your issue with that?

Also, you seem to fundamentally misunderstand how character collections are supposed to work, and appear to not have automatic character redrawing enabled nor tried redrawing your character that you setup a collection for manually, or tried to use mods on it that do not apply on redrawing.
The newest update has a more detailed explanation which you might want to read.

**Comment by Rapsket** [comment]
> You enable interface stuff in Forced.

Incorrect.
Forcing redraw in chat, or toggling the enable mods tickbox in the UI does not fix the issue.
Automatic character redrawing is on.  
I've provided another mod example that has the same problem. 
Having grabbed a few random mods, IE (Hrothgar Oral Care) seem to work, but the two examples above do not - until they are also enabled in a collection assigned to "Default"

**Comment by Ottermandias** [comment]
Yeah, okay, so you have fundamentally misunderstood how character collections work.

**Comment by Ottermandias** [comment]
Sorry for snide remark, the issue in general (you assuming things have to work where they don't necessarily will and your tone about it) still persists, but you drove me to checking something out and I found a stupid bug through it that might fix your problem with the hats, too.

So thanks!

**Comment by Rapsket** [comment]
Appreciate you checking. 
I'm not particularly receptive to being 'splaned' to and being told to RTFM especially when I've provided reproducible reports. I wasn't intending to have any 'tone' - I intended to be concise. I apologise if it was taken the wrong way.

I had read [Issue 96](https://github.com/xivdev/Penumbra/issues/96) with very similar symptoms and tried to perform their remediation with no luck. Also, it seems that the previous update for penumbra didn't refresh/update some UI as expected, because after doing exactly what #96 did, a ton of (i) symbols suddenly appeared, including the new popup for collections. But that's a separate issue that I don't think I can reproduce.

I tried pulling apart the code to identify where the prioritisation for default vs forced vs collections occurred when creating the ModCollectionCache (I assume that is where it checks which mods to apply on redraw) to find out if "enabled" was somehow being ignored but I only spent about half an hour on it and don't have any of the dependencies to test.

**Comment by Rapsket** [comment]
Updated to 0.4.7.0  - its fixed both the hats and the HRbody mod on character collections. I'll test it on the rest of my mods. Thanks for the quick work.

**Comment by PrincessRTFM** [comment]
You said you don't understand the point of a forced collection. I was trying to explain the point of it. Nowhere was my intention to solve your bug report.

**Comment by Rapsket** [comment]
> You said you don't understand the point of a forced collection. I was trying to explain the point of it. Nowhere was my intention to solve your bug report.

I said I didnt understand the point of it. Not that I didnt understand how it functions. That comment was marked as an aside in context of a bug that was only worked around by messing around with forced and default collections, and has subsequently been resolved.
