### ISSUE TITLE
Can't create a new collection

### ISSUE THREAD

**Issue by Troykakaa** [xivdev/Penumbra#114]
No matter what I do, I cannot make a new collection. The option is greyed out no matter if there's anything typed or not
![image](https://user-images.githubusercontent.com/97231166/148723330-3043f19f-4057-47a2-9bb3-90f53023e9c4.png)

**Comment by Ottermandias** [comment]
Have you tried reading the help text?

**Comment by Ottermandias** [comment]
Are you absolutely sure you have actually read the help text?
Can you go to %appdata%\XIVLauncher\pluginConfigs\Penumbra.json and send it to me?

**Comment by Troykakaa** [comment]
> Are you absolutely sure you have actually read the help text? Can you go to %appdata%\XIVLauncher\pluginConfigs\Penumbra.json and send it to me?

Apologies for the late response, I got the creation of collections working, but I still have the issue of my collection not staying on my character between zones. here is the .json if you still need it.
[here you go.zip](https://github.com/xivdev/Penumbra/files/7862044/here.you.go.zip)

**Comment by Ottermandias** [comment]
You don't have automatic redrawing on.

**Comment by Troykakaa** [comment]
> You don't have automatic redrawing on.
Ah, got it. Is there a way I can make it only redraw my character and not everyone around me? It likes to crash whenever I pop by limsa due to the sheer amount of people.

**Comment by Ottermandias** [comment]
It only ever automatically redraws the actors that you have a collection setup for. Which is just you and "Carbuncle" (which may or may not be a bad idea)

**Comment by Troykakaa** [comment]
> It only ever automatically redraws the actors that you have a collection setup for. Which is just you and "Carbuncle" (which may or may not be a bad idea)

That was certainly the issue, lol. Thanks for being patient with me, everything is fixed.
