### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by mayatyler** [xivdev/Penumbra#12]
i imported a mod pack and now anytime i load the launcher it crashes only started happening after i imported a big modpack but not sure

**Comment by NotAdam** [comment]
delete the last modpack you imported or edit `collection.json` and disable them

there'll be some proper crash handling eventually

**Comment by mayatyler** [comment]
yea won't lie might just be dumb but can't find it

**Comment by reiichi001** [comment]
It should be wherever you set your mod files path. (The default is `D:/ffxiv/fs_mods/`)
