### ISSUE TITLE
[Suggestion] Some QoL changes for the mod menu

### ISSUE THREAD

**Issue by ladybunne** [xivdev/Penumbra#120]
Hi there! I've been using Penumbra for the last few days and I think it's fantastic. I'm thinking of making a pull request with the following changes:

- doubleclick a mod to toggle enabled/disabled
- use up and down arrow keys to move to next/previous mod in list
- a rightclick context menu on mods (enable/disable, delete, etc.)
- add "Expand All" and "Collapse All" to the rightclick menu of folders

Would these changes be welcome?

**Comment by Ottermandias** [comment]
- I'm not sure if I like that since double clicks easily happen by accident, but if you couple it with a config option it's definitely fine.
- Sure
- Not sure if needed, but sure, why not.
- Sure
