### ISSUE TITLE
Mods are not loading whatsoever

### ISSUE THREAD

**Issue by Vynland-dev** [xivdev/Penumbra#122]
Hello, one day suddenly Penumbra stopped functioning. I've tried several reinstalls, changing the mod folder but to no avail. I cownloaded a single random mod as an example

Settings:
https://i.imgur.com/Rhk0BKD.png

Collection:
https://i.imgur.com/frJWtZH.png

Installed Mods:
https://i.imgur.com/8wLa0JM.png

Changed Items:
https://i.imgur.com/gQORAPp.png

Debug Tab:
https://i.imgur.com/g7518ZM.png

**Comment by Vynland-dev** [comment]
Completely reinstalling XIVlauncher fixed it.

**Comment by Ottermandias** [comment]
I don't know why completely reinstalling XIVLauncher changed anything, but it is pretty normal that no mods are loading when you have no collection active.
"Default Collection" - "None".
