### ISSUE TITLE
[Bug] Invisible modded models occuring randomly

### ISSUE THREAD

**Issue by BSoD38** [xivdev/Penumbra#131]
I have been facing a long-standing issue with Penumbra where modded models will not load at all at random moments.

When this issue occurs, it seems that ALL modded models will fail to load on my character (this spreads across multiple mods that have no relation to one another).

For example, in this screenshot, I use the latest version of Hrothgar and Viera Hats for the head gear/hair, Unofficial HRBody 2.6 (4K textures, SFW settings) for body and feet models and textures, and hrBody Pagos Shirt. All three failed to load at the same time :
![Raycat](https://i.imgur.com/TthQqPN.png)

It is interesting to note that modded textures load without issues (as you can see the calves in the screenshot, which have HD body textures), but all modded 3D models don't display at all.

This issue will mostly occur when automatic character redrawing occurs after a loading screen. It happens most often when entering a duty. It can also happen when streaming in characters in normal gameplay, but is less frequent.

As always, using `/penumbra redraw` will fix all issues.

**Comment by Ottermandias** [comment]
Tried setting the delay higher?

**Comment by BSoD38** [comment]
> Tried setting the delay higher?

I've tested a bit with setting some delay, and it does seem to help.

I think this is caused by the fact that I play the game at a rather high framerate. The game is usually running at around 80-120 FPS, and since the plugin waits for a number of *frames*, the absolute time that the plugin will wait for character redraws will vary depending on my current framerate. This makes some of the mods not load correctly when my framerate is very high.

Wouldn'it be better to change the "wait frames" into a "wait milliseconds" system instead? It would avoid these kinds of problems.
