### ISSUE TITLE
[Feature Request] Option for limiting amount of redraws 

### ISSUE THREAD

**Issue by Mampamp** [xivdev/Penumbra#140]
I have been trying to run Penumbra alongside CMTool so that I can change gearsets without needing new glamor plates.  This mostly works fine but if I have automatic character redraws on while keeping my gear "frozen" on CMTool, my character will start to get repeatedly redrawn every 5~20 seconds or so.  

This seems to be an issue with how penumbra detects automatic redraw alongside CMTool because if I turn off automatic redraws but use /penumbra redraw, it will load in properly with no issues and no further redraws.  It seems like something that CMTool does to set equipment will continuously trigger redraws even when no gear is being changed.  

Because this is a niche issue, there might be a quick work around if penumbra had an option to limit redraws to once (or some desired amount) per instance.  That way penumbra can still handle initial load in redraws automatically without the false redraw triggers from CMTool.

**Comment by Ottermandias** [comment]
Penumbra has to redraw on every appearance change. Such an option would completely invalidate that feature.
Disable automatic redrawing or your character collection, stop pseudo-freezing values or just use Glamourer instead of CMTool.
