### ISSUE TITLE
Setting to hide Miqo'te ears on helmets does not work

### ISSUE THREAD

**Issue by Werns** [xivdev/Penumbra#160]
I use a mod that replaces the Bunny Crown on female Miqo'tes with Viera ears. It also hides the Miqo'te ears using the same setting that the Werewolf Ears do.

The model replaces correctly when loaded with Penumbra, but the Miqo'te ears are not hidden. I don't recall the name of the setting but it's pretty obvious when you look into the settings for helmets.

https://www.xivmodarchive.com/modid/38916

**Comment by Werns** [comment]
So, I pretty much gave up on this at the time of posting. Just earlier today I tried it again and found a fix. When importing the mod, it did not import equipment parameters, so I had to do that manually. This is part of the mod and works automatically when imported to TexTools, so I don't see why it should work otherwise with Penumbra. 
![image](https://user-images.githubusercontent.com/12315835/175761795-32775c03-86a4-43e6-9a2b-0abad173db67.png)

**Comment by munkviken** [comment]
Remove, then reimport the mod. You might need to remove the mod folder manually through windows explorer in the penumbra mod directory. When editing the meta manipulation make sure you have selected the right option group in the top right. 

Your initial issue was opened on an old version that handled metadata differently. There is no reason why this shouldn't work on the latest version, so you are most likely missing some steps.  Join the discord for better dupprt

**Comment by Werns** [comment]
"an old version that handled metadata differently"

That makes sense. Not worth the hastle right now, though. I got it work so I'll let sleeping dogs lie, but I will remember this post if I ever need to redo things in the future. Thanks.
