### ISSUE TITLE
Audio Problem while using Penumbra

### ISSUE THREAD

**Issue by WillianBK** [xivdev/Penumbra#168]
I'm experiencing some weirdd noises while walking and sometimes the ambient sound or music just stop, but only when using penumbra plugin.

Don't know what i need to post here to show that kind of problem, but that's the max i can explain while playing.

**Comment by Ottermandias** [comment]
If you are not using any sound mods, enable advanced settings, then uncheck 'Disable Audio Streaming'.
If you are using any sound mods, you need to decide if those are more important than the SE bug.

**Comment by WillianBK** [comment]
After some time testing, it does solve the problem, thanks Ottermandias
