### ISSUE TITLE
Foot gear importing as Expeditioner's Thighboots

### ISSUE THREAD

**Issue by Gerardizard** [xivdev/Penumbra#169]
I've noticed this on a couple of mods, where instead of importing the assets from the modpack, Penumbra just loads the Expeditioner's Thighboots for some foot gear. [Here's a couple of screenshots](https://imgur.com/a/kvh5XDL) showing the mod as Penumbra imports it vs how TexTools imports it (which is correct), and [here's the mod](https://www.patreon.com/posts/60177591) I'm importing in the screenshots. In the screenshots I died the foot gear white and the pants black, hopefully that helps ti figure out what's going on in the image. (It also looks to me like #165 is happening here too, since the modded boots don't seem to be overriding the metadata of the highland boots.)

Thanks!

**Comment by Gerardizard** [comment]
I did some playing around with my mod setup, and I think this is caused by a weird interaction between TexTools and Penumbra. It seems to me like importing mods into TexTools quickly (like importing one while there's still a processing queue in TexTools) corrupts something and leads to Penumbra behaving the way I described. So the good news is that by going slowly with my TexTools mods, I was able to get Penumbra working properly. The bad news is this is altogether very mysterious

**Comment by Ottermandias** [comment]
TexTools corrupts your game files by design. If you ever update the game without disabling them completely your game is and stays corrupted until you start over or repair it otherwise.
There should not be a need for you to do anything via TexTools.

**Comment by Lionheart237** [comment]
If Penumbra didn't make the game hang for a long loading period on startup, sure, not using TexTools would be an option, but using TexTools for base mods with Penumbra for situational ones is ideal.

**Comment by Ottermandias** [comment]
If TexTools didn't corrupt your game files penumbra wouldn't hang for a long loading period on startup.
