### ISSUE TITLE
[Bug?] Per-character VFX/animations not working

### ISSUE THREAD

**Issue by thetrueyoshifan** [xivdev/Penumbra#180]
When setting an animation mod to be for a specific character, it doesn't apply. I believe this is timing related, as similar things happen when you set a collection right before doing an animation, and you have to do a second animation to get the custom one to kick in.

**Comment by Ottermandias** [comment]
![image](https://user-images.githubusercontent.com/70807659/162495797-8c310742-4182-4afc-aa1f-10a7c69f86fd.png)
for fucks sake
