### ISSUE TITLE
Mods Not Changing Items

### ISSUE THREAD

**Issue by ShadieFox** [xivdev/Penumbra#185]
Hello! My penumbra won't edit any items from any mod, effectively doing nothing in my dalamud plugins. I've tried fully uninstalling Penumbra, but that didn't seem to work. This has been not working since before 6.1 was released, but wasn't an issue as I could just use TexTools. What might be wrong here?
![image](https://user-images.githubusercontent.com/103748457/163566259-b4aac616-cd5c-4dd0-a221-29f23698ee70.png)

**Comment by Ottermandias** [comment]
Set your default collection.

**Comment by ShadieFox** [comment]
it really was that simple huh. thank you!
