### ISSUE TITLE
Unable to install 0.4.8.2

### ISSUE THREAD

**Issue by Kaethela** [xivdev/Penumbra#187]
Trying to install the latest update via Dalamud is giving an error:

Failed to install plugin Penumbra. Please restart your game and try again. If this error occurs again, please contact the plugin author.

Closing and restarting the game as suggested does not help.

![image](https://user-images.githubusercontent.com/22601892/163650312-d224a3f2-92c5-48b6-b0e5-0785469e2729.png)

**Comment by reiichi001** [comment]
1. Close the game.
2. Go to `%appdata%\xivlauncher\installedPlugins\` 
3. Remove the `Penumbra` folder
4. Launch the game
5. Install Penumbra

Let us know if the issue still persists after that. And if it does, please attach your `dalamud.log` file here.

**Comment by Kaethela** [comment]
Issue persists. Log file attached.

[dalamud.log](https://github.com/xivdev/Penumbra/files/8498872/dalamud.log)

**Comment by Ottermandias** [comment]
```
2022-04-16 00:15:59.241 +01:00 [ERR] [LOCALPLUGIN] Error while loading Penumbra
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.IOException: The file or directory is corrupted and unreadable. : 'H:\ffxivmods\Tight&Firm-Gen3Body-Installer\Feet_ NPC\Feet\chara\equipment\e9903'
 ```
 yeah, uh... try deleting that folder/file? I dunno. That doesn't sound good. Maybe check your hard drive's health.

**Comment by Kaethela** [comment]
That was indeed the issue, looking further into stuff on my own side but this is all good now.
