### ISSUE TITLE
Importing and managing mods is taking 10x longer

### ISSUE THREAD

**Issue by Joahkiin** [xivdev/Penumbra#189]
This issue started happening after the 6.1 update.
Before that, enabling and disabling mods took nothing but an instant, but now they take 4-20 seconds. Importing mods (even small ones) takes about a minute or so.

The only thing I remember doing before the patch was experimenting with the collections options. I've disabled them now, so I don't think that could be it.

It's frustrating to use Penumbra now. Any help? 

**Update:** I tried to reset the plugin settings through Dalamud, and then disabled and re-enable it. It didn't work (560 unorganized mods now, rip).
Also, it seems that mods without configuration options still activate instantly. Importing them still takes forever.

**Update 2:** I've deleted these folders:
...\AppData\Roaming\XIVLauncher\pluginConfigs\Penumbra
...\AppData\Roaming\XIVLauncher\installedPlugins\Penumbra
And then, after reinstalling the Penumbra plugin, I selected a clean folder for the root directory. The problem still persists.

**Comment by Ottermandias** [comment]
I assume you broke your indices by not having cleaned up your install from TexTools' corruption and patching and Penumbra is showering you with exceptions that it can't read the meta tables from lumina. 
Literally nothing changed on Penumbras side that would influence that.

**Comment by Joahkiin** [comment]
Thanks for the reply.
I'm wondering if my game broke because XIVLauncher crashed while it was downloading the 6.1 update. I'm certain I did a start over with TextTools.

At any rate, I've re-downloaded the game, but I might only be able to play and check Penumbra tomorrow.

**Comment by Joahkiin** [comment]
It works perfectly now!
Thank you Ottermandias, if it weren't for your help, I wouldn't have considered reinstalling the game any time soon. ☺

**Comment by Ottermandias** [comment]
Occasionally just completely redownloading FFXIV is probably not even a bad idea, but for further reference:
To my knowledge, you do not need to fresh-install the game to fix TTs corruption issues. Usually, a Start-Over in TexTools is enough, and when it is not, the Quicklauncher provides a custom integrity check that will only redownload the corrupted files.
But good to hear that its working fine afterwards. :)
