### ISSUE TITLE
Enable / Disable mods without restarting

### ISSUE THREAD

**Issue by Kwehh13** [xivdev/Penumbra#193]
Mods dont disable / enable until I restart my game. Setting priority also doesn't change them.

**Comment by Chameleon-Ifi** [comment]
i have the same problem. I uninstalled and installed penumbra and I change the Modfolder. without success.

**Comment by Ottermandias** [comment]
What mods?

**Comment by Chameleon-Ifi** [comment]
all ff14 Mods ... hair, cloth, accessoires. All mods dont work.

**Comment by reiichi001** [comment]
(be specific. Link some as examples)

...also post your dalamud.log file, found in `%appdata%\xivlauncher\`

**Comment by Chameleon-Ifi** [comment]
https://drive.google.com/file/d/1f1iR7yP2q_NTTL77VjxYlbDoWLUnMRV2/view?usp=sharing, https://drive.google.com/file/d/1fY2GmtYSeowCKaMy-iRHDm2RyHFZLQ9G/view?usp=sharing

**Comment by reiichi001** [comment]
> https://drive.google.com/file/d/1f1iR7yP2q_NTTL77VjxYlbDoWLUnMRV2/view?usp=sharing, https://drive.google.com/file/d/1fY2GmtYSeowCKaMy-iRHDm2RyHFZLQ9G/view?usp=sharing

Textools has fucked your game client to a point that any lumina-based plugin (penumbra is one of many) is likely unable to function correctly.
1. Make backups/exports of your mods if needed. (Not as a backup modpack, basic. ...or if you have a copy of the original TTMPs, even better)
2. Open XIVLauncher and right-click on the login button. Choose "Repair"
3. Wait for XIVLauncher to unfuck the game install for you
4. Launch.
5. Import your mods using Penumbra. Don't mix Textools and Penumbra.

**Comment by Chameleon-Ifi** [comment]
ok thx. it is working now <3

**Comment by CappnDub** [comment]
I tried doing that and it's still not working
