### ISSUE TITLE
Problem when attempted to boot ffxiv with penumbra active.

### ISSUE THREAD

**Issue by HishuHana** [xivdev/Penumbra#196]
I don't have very many active options loaded in the list for penumbra but have noticed that when I attempt to turn on or off a mod or change load priority, as well as simply start up ffxiv with penumbra in my plugins that there is a near 2 to 5 minute freeze, this has been since the most recent update as of 4/26 so it seems to be a new issue as before that everything loaded with no issues and there have been no changes made to my selected mods, have attempted to remove the plugin entirely and start fresh however as soon as I readd it the problem starts up again, best case are long freezes or what appear extended load times, worst case penumbra experiences an error and requires that I restart ffxiv entirely which entails another long wait for things to start up.  have tried without penumbra and things load with none of the freeze or delay, just figured I'd try to let you know just incase anyone else is experiencing a similar issue.

**Comment by Ottermandias** [comment]
TexTools fucked your install, Penumbra is throwing a fit because it can't read game files.
Start over in TexTools.

**Comment by ArcaneDisgea** [comment]
If you are using xivlauncher please try the repair option by right clicking the login button and selecting repair.

**Comment by HishuHana** [comment]
that worked, also had to redo everything I had on penumbra it fixed, was odd had never had it happen but now I know what to do to try an rectify in the future ty.
