### ISSUE TITLE
Mods not loading at all.

### ISSUE THREAD

**Issue by ArtsyEinstine** [xivdev/Penumbra#199]
I've been having this issue for about a week or so now and was hoping updates will fix this. This issue occurred after I made folders within the plugin menu to organize my mods. I basically even deleted the folder i had for penumbra, remade it for a clean slate and redirected it to said folder. But the mods still won't load anymore.

**Comment by Ottermandias** [comment]
Show your settings. Main settings tab and collection tab.

**Comment by ArtsyEinstine** [comment]
![image](https://user-images.githubusercontent.com/45639535/166265335-c1599f01-3b5a-4a84-b781-1be48edb8a62.png)
![image](https://user-images.githubusercontent.com/45639535/166265609-33d0baba-f0eb-49f2-8016-5c2c873c999e.png)

**Comment by Ottermandias** [comment]
Default Collection None -> Nothing is applied. Set that to Default.
Enable Mods Off -> Penumbra does absolutely nothing. Toggle that on.

**Comment by ArtsyEinstine** [comment]
Omg thank you so much! I can't believe I didn't notice the collection being turned off, must have screwed it up while organizing! I appreciate it a lot!
