### ISSUE TITLE
Penumbra no longer applies animation mods

### ISSUE THREAD

**Issue by LLingshen** [xivdev/Penumbra#210]
Previously, Penumbra could apply a simple animation mod like say DRK idle on SAM idle, but this new iteration isn't able to anymore. More complicated animation mods with VFX never did work correctly, but for just motion mods, I wish this worked again.

**Comment by Ottermandias** [comment]
Use them in the default collection AND the respective character collection (if one exists) for the moment.
I'm working on getting them to work purely in character collections, but it's fucking hard.
