### ISSUE TITLE
Audio problems

### ISSUE THREAD

**Issue by TheodoreKaiju** [xivdev/Penumbra#213]
Audio keeps cutting in and out whenever I move. It immediately stops when I uninstall penumbra.

**Comment by Nullsloth** [comment]
Also having these issues since Endwalker release. Turning off a setting under Penumbra>Advanced>Enable Sound Modification makes it stop. Wish there was another way to fix it as  it stops you from using modified game sound files.

**Comment by SerenitySunfire** [comment]
This is an SE bug that can be made worse using Penumbra, but not a bug directly caused by Penumbra. This is up to SE to fix.

**Comment by TheodoreKaiju** [comment]
Thanks, I'll check it out.
