### ISSUE TITLE
PluginLog.Verbose Spam

### ISSUE THREAD

**Issue by InitialDet** [xivdev/Penumbra#215]
Would it be possible to comment/remove these PluginLog lines?
https://github.com/xivdev/Penumbra/blob/f6772af246ec7528bc7af26bc574b4df76407e03/Penumbra/Interop/Resolver/PathResolver.Material.cs#L84-L92

They are used so often that it makes the dalamud.log file almost entirely made of these debug lines.

![image](https://user-images.githubusercontent.com/13919114/173464357-545e4f24-ebac-4e5e-aec6-ae1547558603.png)

**Comment by reiichi001** [comment]
It sounds like you're on a development version of Dalamud or purposely enabled verbose logging, which is off by default.  You can set it back to `information` (the default and recommended) logging level from either the `/xldev` menu or from the `/xllog` window's settings.
![image](https://user-images.githubusercontent.com/10376708/173497189-673674f5-991f-48db-aed5-14630e85b3b2.png)

**Comment by Ottermandias** [comment]
Also, in direct response to your question: No.
