### ISSUE TITLE
Ignore non-mod-content files in TT modpack imports

### ISSUE THREAD

**Issue by PrincessRTFM** [xivdev/Penumbra#22]
Since TexTools modpack files are basically zipfiles, a number of authors add non-mod-content files like screenshots, which seems to break Penumbra's importer. Would it be possible to disregard such files when importing?

**Comment by NotAdam** [comment]
can you provide a link to a modpack that's broken?

**Comment by PrincessRTFM** [comment]
The [T&F2 Body (SFW)](https://www.xivmodarchive.com/modid/485#files) (main file) was having that issue when I was helping a friend get started with Penumbra. After opening up the file in winrar, I found a bunch of images. Once I cleared out everything but the `TTMPD.mpd` and `TTMPL.mpl` items, Penumbra was able to import it just fine.
