### ISSUE TITLE
Replacing target files?

### ISSUE THREAD

**Issue by grimdour** [xivdev/Penumbra#222]
Hi, not an issue but more a question:

What's the process for replacing destination paths on a mod? I have a hair mod that targets one hairstyle, but I'd like it to change the destination to another. Is that possible, or do I need to create a textools backup with those settings then apply it via Penumbra?

**Comment by Ottermandias** [comment]
There is no automatic option for this in Penumbra. You can do it manually (which is complicated and effort), or create the mod for the correct thing you want in TT and then import it in Penumbra.
