### ISSUE TITLE
No "select all" function in new import menu?

### ISSUE THREAD

**Issue by zune127** [xivdev/Penumbra#223]
Ever since Penumbra updated to the new import menu, I can only control click to manually select more than 1 mod. In the previous version, I was able to CTRL A to import all the mods at once. Now I have to click each file separately to import, which is a real extra effort when I'm importing 70 mods at once

Is there a keybind or way to fix this beyond going back to the old version?

**Comment by SerenitySunfire** [comment]
Click the top one, scroll down to the bottom, hold down shift and click the bottom one. All should be selected so you can import them.

**Comment by zune127** [comment]
That did it, thank you.
