### ISSUE TITLE
Penumbra (Load error)

### ISSUE THREAD

**Issue by TrueZangon** [xivdev/Penumbra#226]
As of this morning penumbra is not loading through xivlauncher, updated to the lastest release but the issue persists.

**Comment by Ottermandias** [comment]
Do you want to, like... provide any information about that?

**Comment by TrueZangon** [comment]
What information do you need?

**Comment by Ottermandias** [comment]
Anything? Error message, log, did your Dalamud recently update to the Canary version?

**Comment by TrueZangon** [comment]
I believe I figured it out, re-extracting the files and launching as admin seems to have fixed it. I apologize for the wasted time.

**Comment by Ottermandias** [comment]
Launching as Admin is neve a fix.
