### ISSUE TITLE
Body mod in character collection stops working after switching gear

### ISSUE THREAD

**Issue by Breadqt** [xivdev/Penumbra#228]
so basically I have my default collection that has 2 files for my body mod and a separate main file. all three are also in my character collection but the last file has a couple settings changes for my character only. the problem comes when i try and put gear on (in this case emperors gear to make sure everything worked with that aswell). after putting the gear on my character would go back to the default collection settings and any time I would try and change the settings on my character collection nothing would happen. I tried enabling and disabling the mod and redrawing my character but I cant get the settings on the character collection to work. i am able to disable the mods from the character collection without disabling it in default collection and that effects it so it seems just the settings i was using initially are effected. also i had automatic redraw turned off.

**Comment by munkviken** [comment]
Automatic redraw isn't even a thing anymore in Penumbra, what version are you on?

**Comment by Breadqt** [comment]
hmmmmm you know I think im starting to figure out what my problem is.... i got my penumbra from dalamuds experimental tab I didnt even think to check the version

**Comment by munkviken** [comment]
You should only install penumbra through the repo link in the experimental tab. The current version is 0.5.3.1. You will still need to update it through the plugin installer if you don't have auto-updates turned on. Do not download any zip from github.

**Comment by Breadqt** [comment]
i think i used an outdated link from the repo browser got the new one but im running into some errors downloading it but thats a different issue. hopefully once ive figured that issue out this issue will have been solved by using the newest version
