### ISSUE TITLE
TTMP2 Import does not handle symbols

### ISSUE THREAD

**Issue by Gazzoo-byte** [xivdev/Penumbra#23]
If a TTMP2 is authored with a symbol in it's name, Penumbra does not correctly parse this when using the Import TexTools Modpacks button and has an incorrect file path when trying to load the intended mod.

![image](https://user-images.githubusercontent.com/73721238/114295984-a6464500-9aa0-11eb-81bb-9031ce9901bb.png)

![image](https://user-images.githubusercontent.com/73721238/114296072-11901700-9aa1-11eb-9d40-b6e13404a535.png)

**Comment by NotAdam** [comment]
the game doesn't support file paths like this either, it's rendering incorrectly in penumbra's UI but the game requires that files and folders be ascii only.

will add sanitisation in penumbra but this isn't exactly something that the game supports at all

**Comment by Aida-Enna** [comment]
As a workaround, you can (making sure the game is closed first), rename the folder the mod files are stored in (that has the non-supported characters) and change the path it's looking for in the collection,json where your mod files are stored.

For example, if I try to install a mod and it creates a path called ``C:\Mods\机枪散射V2``, I would rename it the folder to something like ``C:\Mods\SpreadShotV2`` and then change it in the collection.json from ``{"FolderName":"机枪散射V2","Enabled":true,"Priority":5,"Settings":{}}`` to ``{"FolderName":"SpreadShotV2","Enabled":true,"Priority":5,"Settings":{}}``
(Please note that your priority number will likely be different).

Maybe Penumbra can detect filenames with UTF-8 characters/invalid characters and remove them from the created folder path?
For example, ``机枪散射V2`` would become ``V2``. Not exactly great, but better than not working at all, lol. Maybe an autogenerated name? ``机枪散射V2`` -> ``Invalid Mod Name (V2)`` or something. The meta information having invalid characters is fine, it's just the folder path that breaks it.

**Comment by Aida-Enna** [comment]
Ah, this appears to have been fixed for a while? Attempting to install the mods that previously didn't work now creates the foldernames with "_" replacing the unsupported characters.
