### ISSUE TITLE
Penumbra IMC file error

### ISSUE THREAD

**Issue by pschwaab** [xivdev/Penumbra#234]
Hi everyone,
I ran into an issue where penumbra would not load 9 INC files and therefore wouldn't work. It suggested I repair game files, which I did by deleting all my textools mods. then going into xivlauncher and right clicking log in, and then repairing game files. Afterwards, I reinstalled my backup of my textools mods, then went back into the game after installing gshade, and I had the same issue. It was working just fine before with my textools mods+penumbra mods. Any suggestions on how to fix this? Thanks!

Here is my support info
**Settings**
> **`Plugin Version:              `** 0.5.3.7
> **`Commit Hash:                 `** e6a4cb9
> **`Enable Mods:                 `** True
> **`Enable HTTP API:             `** False
> **`Root Directory:              `** `S:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY XIV Online\penumbra`, Exists
> **`Free Drive Space:            `** 236.6 GB
**Mods**
> **`Installed Mods:              `** 10
> **`Mods with Config:            `** 3
> **`Mods with File Redirections: `** 9, Total: 331
> **`Mods with FileSwaps:         `** 0, Total: 0
> **`Mods with Meta Manipulations:`** 3, Total 472
> **`IMC Exceptions Thrown:       `** 9
**Collections**
> **`#Collections:                `** 1
> **`Active Collections:          `** 1
> **`Default Collection:          `** De... (1)
> **`Current Collection:          `** De... (1)
**Collection De... (1)**
> **`Inheritances:                `** 0
> **`Enabled Mods:                `** 4
> **`Total Conflicts:             `** 0
> **`Solved Conflicts:            `** 0

**Comment by munkviken** [comment]
You can't reinstall your backup of TexTools mods. That is what broke your indices the second time as well. Do the repair again, but do not install anything in TT.

Combined use of TT and Penumbra is not recommend because of this. It is very likely that TT eventually corrupts your index files and causes the issue you are experiencing. Your backup modpack will just repeat the issue at this point, sadly.

**Comment by pschwaab** [comment]
Okay thanks for the info. I think I'll just not use penumbra for now, until I manage to move my mods over to it instead. Thanks.
