### ISSUE TITLE
Dalamund Update Broke Penumbra

### ISSUE THREAD

**Issue by MGDHati** [xivdev/Penumbra#237]
After Dalamund just updated I'm getting "This plugin failed to load. Please contact the author for more information. When I try to play the game it then crashes.

**Comment by reiichi001** [comment]
Hey there! This is Franz from XIVLauncher/Dalamud/etc. (I also sometimes help out with Penumbra support)

Is this issue still occurring post-repair?

**Comment by MGDHati** [comment]
No, your earlier email with having me do the repair with another plug-in worked. However I can’t get GShade to work with Dalamund now no matter what I do.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
