### ISSUE TITLE
Many Job Icon Mods doesn't work

### ISSUE THREAD

**Issue by tmschorr** [xivdev/Penumbra#238]
I tested with Black Edge Icon Pack (doesn't work), Gear Set Icons Revamped (doesn't work), Blended Job Icons (doesn't work), GlowyIcons (it worked).

**Comment by Ottermandias** [comment]
Either the icons are not replacing the _hr icons or are replacing the _hr icons and you're not using high resolution, or you'd just need to restart, or your config is bad.

**Comment by tmschorr** [comment]
I have already tried everything possible
Could you look at the 2 .json files and tell if there is an error?

default_mod.json:
{
  "Name": "",
  "Priority": 0,
  "Files": {
    "ui/icon/062000/062042_hr1.tex": "ui\\icon\\062000\\062042_hr1.tex",
    "ui/icon/062000/062101_hr1.tex": "ui\\icon\\062000\\062101_hr1.tex",
    "ui/icon/062000/062102_hr1.tex": "ui\\icon\\062000\\062102_hr1.tex",
    "ui/icon/062000/062103_hr1.tex": "ui\\icon\\062000\\062103_hr1.tex",
    "ui/icon/062000/062104_hr1.tex": "ui\\icon\\062000\\062104_hr1.tex",
    "ui/icon/062000/062105_hr1.tex": "ui\\icon\\062000\\062105_hr1.tex",
    "ui/icon/062000/062106_hr1.tex": "ui\\icon\\062000\\062106_hr1.tex",
    "ui/icon/062000/062107_hr1.tex": "ui\\icon\\062000\\062107_hr1.tex",
    "ui/icon/062000/062108_hr1.tex": "ui\\icon\\062000\\062108_hr1.tex",
    "ui/icon/062000/062109_hr1.tex": "ui\\icon\\062000\\062109_hr1.tex",
    "ui/icon/062000/062110_hr1.tex": "ui\\icon\\062000\\062110_hr1.tex",
    "ui/icon/062000/062111_hr1.tex": "ui\\icon\\062000\\062111_hr1.tex",
    "ui/icon/062000/062112_hr1.tex": "ui\\icon\\062000\\062112_hr1.tex",
    "ui/icon/062000/062113_hr1.tex": "ui\\icon\\062000\\062113_hr1.tex",
    "ui/icon/062000/062114_hr1.tex": "ui\\icon\\062000\\062114_hr1.tex",
    "ui/icon/062000/062115_hr1.tex": "ui\\icon\\062000\\062115_hr1.tex",
    "ui/icon/062000/062116_hr1.tex": "ui\\icon\\062000\\062116_hr1.tex",
    "ui/icon/062000/062117_hr1.tex": "ui\\icon\\062000\\062117_hr1.tex",
    "ui/icon/062000/062118_hr1.tex": "ui\\icon\\062000\\062118_hr1.tex",
    "ui/icon/062000/062119_hr1.tex": "ui\\icon\\062000\\062119_hr1.tex",
    "ui/icon/062000/062120_hr1.tex": "ui\\icon\\062000\\062120_hr1.tex",
    "ui/icon/062000/062121_hr1.tex": "ui\\icon\\062000\\062121_hr1.tex",
    "ui/icon/062000/062122_hr1.tex": "ui\\icon\\062000\\062122_hr1.tex",
    "ui/icon/062000/062123_hr1.tex": "ui\\icon\\062000\\062123_hr1.tex",
    "ui/icon/062000/062124_hr1.tex": "ui\\icon\\062000\\062124_hr1.tex",
    "ui/icon/062000/062125_hr1.tex": "ui\\icon\\062000\\062125_hr1.tex",
    "ui/icon/062000/062126_hr1.tex": "ui\\icon\\062000\\062126_hr1.tex",
    "ui/icon/062000/062127_hr1.tex": "ui\\icon\\062000\\062127_hr1.tex",
    "ui/icon/062000/062128_hr1.tex": "ui\\icon\\062000\\062128_hr1.tex",
    "ui/icon/062000/062129_hr1.tex": "ui\\icon\\062000\\062129_hr1.tex",
    "ui/icon/062000/062130_hr1.tex": "ui\\icon\\062000\\062130_hr1.tex",
    "ui/icon/062000/062131_hr1.tex": "ui\\icon\\062000\\062131_hr1.tex",
    "ui/icon/062000/062132_hr1.tex": "ui\\icon\\062000\\062132_hr1.tex",
    "ui/icon/062000/062133_hr1.tex": "ui\\icon\\062000\\062133_hr1.tex",
    "ui/icon/062000/062134_hr1.tex": "ui\\icon\\062000\\062134_hr1.tex",
    "ui/icon/062000/062135_hr1.tex": "ui\\icon\\062000\\062135_hr1.tex",
    "ui/icon/062000/062136_hr1.tex": "ui\\icon\\062000\\062136_hr1.tex",
    "ui/icon/062000/062137_hr1.tex": "ui\\icon\\062000\\062137_hr1.tex",
    "ui/icon/062000/062138_hr1.tex": "ui\\icon\\062000\\062138_hr1.tex",
    "ui/icon/062000/062139_hr1.tex": "ui\\icon\\062000\\062139_hr1.tex",
    "ui/icon/062000/062140_hr1.tex": "ui\\icon\\062000\\062140_hr1.tex",
    "ui/icon/062000/062141_hr1.tex": "ui\\icon\\062000\\062141_hr1.tex",
    "ui/icon/062000/062142_hr1.tex": "ui\\icon\\062000\\062142_hr1.tex",
    "ui/icon/062000/062143_hr1.tex": "ui\\icon\\062000\\062143_hr1.tex"
  },
  "FileSwaps": {},
  "Manipulations": []
}

meta.json:
{
  "FileVersion": 1,
  "Name": "Black Edge Icon Pack (Job Icons)",
  "Author": "Meconate",
  "Description": "Mod imported from TexTools mod pack.",
  "Version": "3.0.0",
  "Website": "",
  "ImportDate": 1658852451307
}

**Comment by Sevii77** [comment]
That mod is made for 4k ui. The one that worked, glowyicons, isn't. You need to set your UI to 4k.
Quick guide from the Material UI Discord:
![image](https://user-images.githubusercontent.com/20374966/181064453-9bcb5657-5759-474f-8704-29fcefff5399.png)

**Comment by tmschorr** [comment]
It worked now, thank you very much ^^
