### ISSUE TITLE
Enable/Disable all Function not working

### ISSUE THREAD

**Issue by Metaknight3** [xivdev/Penumbra#240]
The new Enable All for multiselects doesn't seem to work for multiselects above 28 options. Disable All works perfectly well but simple enabling does not seem to work. [Mod in Question](https://www.xivmodarchive.com/modid/33163) where Part 1 of each section of 32 can have Disable All, but Enable All fails entirely, unsure if it's badly packaged or has to do with how Penumbra splits options.
No Textools were used, game is fully repaired and produces no errors, problem seems to persist.

**Comment by Ottermandias** [comment]
It's specifically 32 options, not "above 28", yeah, duh. (1 << 32) - 1 is bad for a 32 bit value.
