### ISSUE TITLE
{Question} Does Glamourer work in cutscenes and weddings?

### ISSUE THREAD

**Issue by Fyrekeeper** [xivdev/Penumbra#246]
I couldn't find a discord link and may have over looked one. Is it possible to use glamourer mid cutscene and have people tried it mid wedding?

**Comment by MadamSerenity** [comment]
Most all cutscenes it does, but may or may not in wedding. I just got married yesterday and my mods worked, but others have said it didn't.

**Comment by MadamSerenity** [comment]
Also, there is a Discord link on the front page under Support.

![image](https://user-images.githubusercontent.com/97070849/185806917-8b20240c-e94c-4c1f-97ce-512f9c7392bc.png)

**Comment by Fyrekeeper** [comment]
> Also, there is a Discord link on the front page under Support.
> 
> ![image](https://user-images.githubusercontent.com/97070849/185806917-8b20240c-e94c-4c1f-97ce-512f9c7392bc.png)

Tysm! I have poor eyesight and didn't think to look for it under support. Appreciate you and glad your mods worked! :)
