### ISSUE TITLE
Cannot Close New Changelog Menu

### ISSUE THREAD

**Issue by Valarien-Ahkayo** [xivdev/Penumbra#249]
![20220910102903_1](https://user-images.githubusercontent.com/113249428/189488144-3f5d5aca-b3ca-41bd-8f94-bd9eb6a5f8ac.jpg)
As the title says, I cannot close or even move the changelog window making it pretty much unusable at the moment.

**Comment by Ottermandias** [comment]
Set global scale to 1, close, revert.
Working on it.

**Comment by Valarien-Ahkayo** [comment]
> Set global scale to 1, close, revert. Working on it.

Thank you, that allowed me to close the window.  Good luck with your fix.
