### ISSUE TITLE
Redraw not working on all NPCs and PCs while in content.

### ISSUE THREAD

**Issue by SkylerMews** [xivdev/Penumbra#25]
While I was in the new Nier Raid **The Tower at Paradigm's Breach** using the command `/penumbra redraw` didn't redraw everyone within the scene. My character was invisible as well as other people within the raid.

The only reason I bring this up is because some people might want to disable some mods while in content and may have forgotten when outside of content.

It seems that when the redraw is done, not everyone gets loaded in, and its somewhat random or who does and doesn't.

I've tried disabling all mods, restarting game, going back into content, and doing a redraw. Same issue occurs.

**Comment by Minescence** [comment]
The player character is also rather prone to disappearing in cutscenes randomly.
