### ISSUE TITLE
Please allow resizing the mod column

### ISSUE THREAD

**Issue by ividyon** [xivdev/Penumbra#251]
When using higher font sizes for Dalamud (ex. for 4K displays), the mod column on the left side under the "Mods" tab becomes painfully constricted and it is not possible to read the file names comfortably.

Please allow drag-resizing the space between the column and the UI on the right size in order to change the amount of available space.

**Comment by Ottermandias** [comment]
![image](https://user-images.githubusercontent.com/70807659/193363522-d60d1457-9146-4505-a1fb-0ea1d79d1932.png)
