### ISSUE TITLE
Penumbra Outdated?

### ISSUE THREAD

**Issue by UmbraBlackscale** [xivdev/Penumbra#252]
Tried setting up Mare, but the Penumbra plug-in is outdated? Any advice would be helpful

**Comment by Theo-Asterio** [comment]
Not outdated. If you haven’t updated Penumbra, use a manual install (bad) or a different repo (outside the official one) please fix these issues first. Not the place to ask either case, would recommend Penumbra Discord where you can be helped further if you provide details.

**Comment by reiichi001** [comment]
Please do not manually install Penumbra or try to get it from somewhere that isn't the official custom plugin repository, which is right there on the main readme. <https://github.com/xivdev/Penumbra>

`https://raw.githubusercontent.com/xivdev/Penumbra/master/repo.json`

If you're getting Penumbra from somewhere else, **stop doing that immediately.** It could have been tampered with. It could be out of date. Or worse, it could be from a reposter repo.

The current version of Penumbra is `0.5.10.0` and it's been out for 11 days at time of writing.

**Comment by Theo-Asterio** [comment]
> @Theo-Asterio while support is preferred to take place on the discord server, this kind of is the right place to ask for help if they don't have/use discord.
Use of Mare requires Discord, that would be why it's preferred rather than mandatory. Noted.

**Comment by UmbraBlackscale** [comment]
Had to completely reinstall and repair XIVLauncher. Fixed. Thanks all
