### ISSUE TITLE
Cannot use variables such as %USERPROFILE% or %USERNAME% for defining root directory

### ISSUE THREAD

**Issue by EpiclyDelicious** [xivdev/Penumbra#255]
It seems when attempting to change the root directory for Penumbra, you are not allowed to use Windows variables for defining the directory path location. Additionally, it does not work even through manually modifying the Penumbra.json file to respect that directory. Unless I am missing something.

i.e **"C:\\Users\\%USERNAME%\\DirectoryHere** or **%USERPROFILE%\\DirectoryHere**

I can explain why this is useful but wanted to keep reporting the issue short.

**Comment by Ottermandias** [comment]
Yes, this is true. Resolving placeholders or environment variables adds a lot of complexity. Any such path is also too long to be recommended, anyway.
So, yeah, whatever.
