### ISSUE TITLE
ttmp2 failed to import due to 'missing path(s)' ?

### ISSUE THREAD

**Issue by Zzuit** [xivdev/Penumbra#256]
![importerror](https://user-images.githubusercontent.com/119240411/204152543-d81166b8-169c-4052-9fb6-396245b842b5.png)
This is the error I'm being presented with upon trying to import a VFX mod for DRK. 

I do not _have_ a D:\ directory so I'm not sure what I'm supposed to do about that but I do have a proper penumbra mod folder. This and one other VFX wont import correctly, however if I use a different one to replace the same thing it works fine. No other mods have had this issue.

**Comment by Ottermandias** [comment]
The TTMP is corrupt. A file in it has no file name.
The D: is referring to the drive where Penumbra was compiled, not yours.

**Comment by Zzuit** [comment]
Well to be honest I have no idea how I can fix that. Thank you for the timely response though.

**Comment by Ottermandias** [comment]
You'd need to contact the mod creator. You could also link the mod here, it's probably an easy fix.

**Comment by Zzuit** [comment]
I'm attempting to contact them now, thank you again.
