### ISSUE TITLE
Selective File Import like textools? Right Click Delete Specific Mod Files?

### ISSUE THREAD

**Issue by KhaozFrost** [xivdev/Penumbra#26]
So textools offers the ability in some cases to be selective about what files from the mod you want to import. Ie. Scale mods
Lets say I want to install a Black/White Scale Mod but only want to import the black scale files and not the vanilla ones; Well with Penumbra you can only import whole mods with no easy ability to remove the files you don't want imported. I was thinking that If textools has the redirect imports to Lumina option checked and its opened via textools then it wouldn't require shutdown of the client, along with inside the Launcher where you 'manage mods' include like a right click ability to delete specific files within a mod listing rather then only being able to delete the mod as a whole?

**Comment by PrincessRTFM** [comment]
If you want to remove files from a Penumbra mod, you can just delete the files from the mod folder
