### ISSUE TITLE
ntdll.dll error with penumbra

### ISSUE THREAD

**Issue by Sazuzaki** [xivdev/Penumbra#27]
Hello, I've been getting crashes on loading screens or when switching classes. No error pops up, so I check event viewer and get this:
 
https://imgur.com/a/wnyutUZ

I've tried:
Reinstalling graphics drivers
Delaying Dalamud injection

The thing that worked for me was playing without Penumbra, so I assume it might be related to fileswap mods I made.

**Comment by Lunaretic** [comment]
This is an issue for the Penumbra guys.  Try their repos/etc.
