### ISSUE TITLE
Item swap broken for hats

### ISSUE THREAD

**Issue by LaaZa** [xivdev/Penumbra#270]
Swapping hats does not work properly. Model does not show, shows non modded model or breaks in other ways.

**Comment by Ottermandias** [comment]
Wow, talk about useless.

**Comment by LaaZa** [comment]
Hey, don't be like that. I just wanted to let you know this new feature has a problem. I can give you more info if you tell me what you need. If you are working on it already then that's fine.

**Comment by Ottermandias** [comment]
Sorry.
Does it still break after 6.1.1?
What pair of hats?
With modded files or entirely vanilla?
If with modded files, what mod?
Breaks for all genders/races, or just specific ones?

**Comment by LaaZa** [comment]
Sorry, I was a bit busy. 
According to my friend the issue is now fixed! 
I will report back if I notice any other issues with it.

Small suggestion though. Wouldn't it be better to use official game terminology for the item slot tabs?

**Comment by Ottermandias** [comment]
I dislike that accessories describe the item while armor pieces describe the position.

**Comment by LaaZa** [comment]
I guess, but all head pieces aren't hats and that difference goes for almost all left slots in a way. All accessories are exactly the item described though to my knowledge. 
I just think it would be less confusing, because people may think they can't change "non-hat" head pieces and they are very familiar with the game's terminology.

**Comment by LaaZa** [comment]
I think this specific issue is fixed.
