### ISSUE TITLE
Game freezes intermittently when rendering Redraw button tooltips with GShade installed

### ISSUE THREAD

**Issue by DigitalMachinist** [xivdev/Penumbra#276]
This is a weird one, but I've been experiencing a lot of crashed within the last week or so when I have the Penumbra UI window open and finally took a few hours to figure out the cause of these game freezes. It seems like GShade is interacting with Penumbra's Dalamud window such that the GShade overlay renders into even individual tooltips, and sometimes the latency introduced by starting up GShade into these new contexts causes the game to freeze and crash.

I've been adjusting my mod setup in Penumbra frequently the last little while and my game is crashing whenever I'm doing that work probably at least 5-10 times per hour, and I'm losing my mind. Now that I understand that its the tooltip at fault, I can cause the game to freeze within about 10 seconds of trying.

I honestly don't know if this is the right place to report this, because GShade isn't your problem. That being said, I don't see GShade trying to render into the windows of or tooltips of other Dalamud plugins, so there's something about how Penumbra's rendering context is set up that's likely at fault.

### Steps to reproduce

1. Install GShade -- You don't even need to turn on any shaders. As long as its overlay renders ingame it will cause the issue.
2. Open Penumbra to the mods panel.
3. Repeatedly hover over buttons in the redraw bar (all/self/target/focus) to cause tooltips to appear on hover until the game freezes.

### Temporary workarounds
- Disable FFXIV installation in GShade so GShade does not run in FFXIV at all.

#### GShade overlay appearing in the Penumbra window
![image](https://user-images.githubusercontent.com/896124/213893884-279f5d2c-905b-4874-9223-f21467d4d193.png)
You can see here that the GShade overlay that appears at game launch is rendering into the Penumbra panel rendered by Dalamud. I have not seen this happen with any other Dalamud plugin, so that's why I'm reporting this here, because I don't think this is a problem with Dalamud itself.

#### GShade overlay appearing in redraw button tooltips
![image](https://user-images.githubusercontent.com/896124/213893998-6f0b1e9d-6c10-442e-b920-7a972639b56e.png)
This is what it looks like when GShade's overlay runs on a tooltip for a button in the redraw bar.

**Comment by DigitalMachinist** [comment]
Some additional details:
- I have tested with GShade using both Normal and Alternate hooking mode, and both behave the same.
- I have tested with all mods disabled.
- I have tested with the top-level "Enabled Mods" flag disabled.
- I have tested with my mods folder completely empty so there's no mods to load.
- I have tested disabling all other Dalamud plugins.

**Comment by NotAdam** [comment]
disable viewports (Enable multi-monitor windows) in dalamud settings

**Comment by DigitalMachinist** [comment]
@NotAdam Just tried it and it seems to resolve it! Thank you!
