### ISSUE TITLE
Fullstop in Name causes parsing and extraction issues

### ISSUE THREAD

**Issue by DaCyclops** [xivdev/Penumbra#28]
Just had a conversation in the XIVLauncher Plugin discord, with a user (AGPhoel) having issues importing mods. When they imported the second mod, it would "remove" the first mod. 
Discord Convo: https://discord.com/channels/581875019861328007/684745859497590843/840030955812290590

Original Pictures Provided.
https://cdn.discordapp.com/attachments/684745859497590843/840032416130924564/unknown.png
https://cdn.discordapp.com/attachments/684745859497590843/840032728589402132/unknown.png

I asked for a shot of the "Files" tab
https://cdn.discordapp.com/attachments/684745859497590843/840033032936751124/unknown.png
Of note, the eventual folder name for the mod was "(v1"

I checked the original mod files - both actually had "(v1.1)" in front of their modnames.
I tried renaming the mods inside the TTMPL.mpl files (removing the version), and passed it the modified versions back to AGPhoel. They were able to import them fine after this.
https://cdn.discordapp.com/attachments/684745859497590843/840036701114990592/unknown.png

It appears that the parsing of the "Name" field, which is used for creating the folder name, stops instantly if it sees a fullstop. In this case, the mods had versions at the start, which caused them to write to the same folders. 

This is a little similar to #23 (as its parsing of the "Name" field not handling things correctly).
But I felt considering this warranted its own issue report.

**Comment by Ottermandias** [comment]
This is probably fixed since quite a while, I'll close it for now :)
