### ISSUE TITLE
Mods no longer loading

### ISSUE THREAD

**Issue by TorieKu** [xivdev/Penumbra#281]
Hiya I have a weird issue, some mods I have just stopped loading. The weird thing though is that not all the mods stopped working. 

I tried reinstalling the mods, downloading new copies from the mod archives, but that didn't work either. 

I don't get any error messages or similar. Only thing that recently happened was me getting a name change, but I don't think I ever had to enter that anywhere?

Thank you for any help in advance, really hoping we can get this figured out. :/

**Comment by Ottermandias** [comment]
Check your collection assignments.

**Comment by TorieKu** [comment]
AHA! That was it. I had to add the new name of my character under Individual Characters.

Thank you very much for the quick help! I am new to modding, so still learning things.
