### ISSUE TITLE
chinese individual character name support

### ISSUE THREAD

**Issue by JetBamboo** [xivdev/Penumbra#283]
Penumbra is a very outstanding work, it gave me a very different ffxiv experience, I am a Chinese player, the character names on our side are not the same as those on the international server, I try to change the "Individual Characters" of "Collections" "Settings to try to assign different mod ranges to different players, sadly when I do the "Assign Player" operation it tells me this is not a valid player name, I'm guessing it's due to wrong name matching rules Caused. If you can support the user name rules in China (six characters, including double-byte characters, symbols cannot be used), I will be very grateful. On behalf of Chinese players, I would like to give you the most sincere respect. Thank you so much !!!

![image](https://user-images.githubusercontent.com/26022145/218519560-29d3ac30-3649-40a2-a7ab-fcfad3aa7d4a.png)

![image](https://user-images.githubusercontent.com/26022145/218519685-f5982840-d3d7-4ac7-8103-8c7993fd2925.png)

**Comment by Ottermandias** [comment]
Sorry, I can not in any way do that. I do not have access to a Chinese client, nor can I read or understand any chinese script or language.
You can poke the maintainers of Penumbras CN fork - BlueFissure, I think? - for that, but mainline Penumbra can't help you out.
