### ISSUE TITLE
[Feature Request] Improvement of Search function in the "Import Mod Pack" screen

### ISSUE THREAD

**Issue by torakiti2017** [xivdev/Penumbra#295]
When you enter text in the "Search" field on the "Import Mod Pack" screen, matching files or folders are filtered.
If a folder is opened with the Search text entered, the Search text will remain as it is.
Is it possible to make the Search text disappear when the folder is opened?

Reason:
The user enters Search to search for the desired mod folder, but even after the folder is opened, the filter is still active, so not all the files in the folder are displayed.

Enter Search:
<img width="225" alt="1" src="https://user-images.githubusercontent.com/86459831/227794505-0291d118-8301-4f29-894a-b9171f6cdd33.png">

Folder is opened (filter remains active):
<img width="246" alt="2" src="https://user-images.githubusercontent.com/86459831/227794515-7f14767e-cacb-4887-ba71-100bad32233e.png">

Actual folder contents:
<img width="273" alt="3" src="https://user-images.githubusercontent.com/86459831/227794536-1599ecec-34a1-4602-a8cf-307e71dba4a0.png">

**Comment by rootdarkarchon** [comment]
I think this needs to be addressed to the Dalamud team as the file picker is Dalamud internal.

**Comment by torakiti2017** [comment]
Thanks for the reply.
https://github.com/goatcorp/Dalamud/issues
Is it preferable to list it in Issues here?

**Comment by NotNite** [comment]
Yes.

**Comment by torakiti2017** [comment]
Thanks for the info.
For mentioning in Dalamud/issues,
This one is closed.
