### ISSUE TITLE
Minimal UI with Penumbra

### ISSUE THREAD

**Issue by Lanselotto** [xivdev/Penumbra#30]
If i open a window, say inventory, the window is the standard one, until i right click something opening a sub menu. The sub menu have the minimal UI texture and then the inventory window too, untill i close the sub menu and the invetory window turn back to standard texture.

**Comment by lmcintyre** [comment]
I use Penumbra with minimal UI and have no issues. If you have not restarted your game, restart it. Otherwise, you need to make sure you're using the correct minimal UI for your UI resolution settings.
