### ISSUE TITLE
Warning: Collection of unsupported name found: is not a valid collection name

### ISSUE THREAD

**Issue by HansYolo** [xivdev/Penumbra#303]
Hi, i'm getting this warning when i start the game. the mods are still loading like normally.

![Screenshot 1](https://user-images.githubusercontent.com/57645543/235898745-d05c4f63-f73d-478e-892a-64017d8d65af.png)
![Screenshot 2](https://user-images.githubusercontent.com/57645543/235898770-a2174fea-f803-4f26-a349-fc9e2e8ec8b9.png)

**Comment by Ottermandias** [comment]
You seem to have a broken collection file with no name in your folder. Go to %appdata%\XIVLauncher\pluginConfigs\Penumbra\Collections and check the files there, remove the one that's not Default, I guess.

**Comment by HansYolo** [comment]
wow thanks for your quickly reply. there was an empty .jason file in there. i don't know where that came from.

**Comment by allainecactuar** [comment]
Yeah, to clarify in case it's helpful for anybody else, I had a file called `.json` with no base filename, just an extension.
