### ISSUE TITLE
Penumbra drops game to 1 FPS when opening PC directory

### ISSUE THREAD

**Issue by sn0wtec** [xivdev/Penumbra#305]
I found this out while trying to import mods. Even happens when trying to change default mod import directory for example.

I press the button which opens the window where you can navigate your PC -> at this second the game becomes unresponsive, the window pops up a second later but I am unable to even navigate or import mods.

I already repaired my install, disabled everything but Penumbra etc. Nothing seems to work.

Can anybody help?

**Comment by Theo-Asterio** [comment]
You were told to go to the dalamud discord, this is not the dalamud discord nor server. This is the Github for Penumbra.

**Comment by sn0wtec** [comment]
I apologize, I just made this issue before I read the reply in the Discord. Thanks for your help.
