### ISSUE TITLE
[Feature Request] Custom collection option for PvP

### ISSUE THREAD

**Issue by V3semir** [xivdev/Penumbra#310]
Hello! I would appreciate it if you could add an option to apply a custom collection for PvP (or maybe a collection per map?). This would allow me to disable most of the mods that I don’t want to use due to performance issues. I couldn’t find such an option in the current version, so I assume it’s not implemented yet. Thank you!

**Comment by Theo-Asterio** [comment]
Make a text macro to disable or swap collections you could just hit when you enter the pvp map, much easier to do. Penumbra has text commands to enable/disable mods or whole collection swapping you can read with /penumbra help/

**Comment by V3semir** [comment]
> Make a text macro to disable or swap collections you could just hit when you enter the pvp map, much easier to do. Penumbra has text commands to enable/disable mods or whole collection swapping you can read with /penumbra help/

Thanks! That would do the job just fine.
