### ISSUE TITLE
Possible to base collections on jobs?

### ISSUE THREAD

**Issue by ShanaGartrex** [xivdev/Penumbra#322]

**Comment by Theo-Asterio** [comment]
No it's not. Glamourer allows fixed designs per job, consider using item swap if you have that many pieces of gear that overlap to need collections per job.

**Comment by ShanaGartrex** [comment]
I didn't get to finish the post as my browser messed up and github posted this without me even finishing the post.

My question was more based on things like the VFX mods or casting animations, swapping jobs having penumbra automatically swapping collections to auto enable/disable mods set to that specific job.

**Comment by Theo-Asterio** [comment]
It's still not possible to set up collections to do so, the only thing you can do is use text macros for penumbra to swap collections with it and change your job at the same time.

**Comment by ShanaGartrex** [comment]
Ah oki. Thanks for answering!
