### ISSUE TITLE
Custom Plugin Repository?

### ISSUE THREAD

**Issue by CasualSuperman** [xivdev/Penumbra#33]
Has there been a decision _not_ to create a custom plugin repository so updates can be applied automatically?
Some examples:
https://github.com/saltycog/DalamudPlugins
https://github.com/LeonBlade/DalamudPlugins

**Comment by PrincessRTFM** [comment]
IIRC, yes. The devs felt it was too early to make Penumbra available on the installer, last I heard.

**Comment by CasualSuperman** [comment]
This wouldn't make it available by default, just make it easier to stay up to date for those who have manually added it.

**Comment by reiichi001** [comment]
That defeats the purpose of "people should know how to manually install the plugin while it's still early in development." AKA a user should not need their hand held through the process. 

Penumbra is currently available for ease of development. 

While nothing stops someone from posting builds on a custom repo, it would probably be frowned upon. Providing pre-built binaries is already a step over what was intended when Penumbra went public before being finished.

**Comment by CasualSuperman** [comment]
> That defeats the purpose of "people should know how to manually install the plugin while it's still early in development." AKA a user should not need their hand held through the process.

That's fair. While I'm capable of installing it manually, it's a minor annoyance to have to update it manually when there's an easy mechanism for doing it automatically, so I figured I'd ask.

**Comment by PrincessRTFM** [comment]
If you're also a programmer, you can do what I did and write your own script to handle it. Download, identify, and unzip the latest release, then replace the old folder with the new one. I hacked out a perl script in like half an hour to do it, and that's counting time looking through the github API response JSON.

**Comment by CasualSuperman** [comment]
Sure I _can_, but my goal was to avoid each programmer using Penumbra duplicating the work to do so.
