### ISSUE TITLE
Penumbra does not show up in /xlplugin search

### ISSUE THREAD

**Issue by cyberstitches** [xivdev/Penumbra#333]
I've restarted the game twice with Dalamud, and penumbra doesn't show up at all as an available plugin no matter how I search for it. Is penumbra currently down, or is it an issue on my end?

**Comment by Theo-Asterio** [comment]
> I've restarted the game twice with Dalamud, and penumbra doesn't show up at all as an available plugin no matter how I search for it. Is penumbra currently down, or is it an issue on my end?

No, Penumbra is up. Penumbra requires you to add the repo, please read both the github and reniguide. https://reniguide.info/
