### ISSUE TITLE
Importing Modpack twice prevents changing the mod anymore.

### ISSUE THREAD

**Issue by SkylerMews** [xivdev/Penumbra#34]
When importing any modpack with the same name as one already installed, Penumbra makes a new folder with a `"(2)"` to the end of the folder name. But this isn't the same folder listed inside of the `"collection.json"`

This makes it to where the mod in Penumbra's list isn't clickable. You can't delete, modify, disable/enable or do anything with this mod. The only fix for this I've seen is to go into your penumbra data folder and delete the duplicate folder with the `"(2)"` in it's name.

Steps to reproduce: 
1. Install any TTMP file.
2. Install that same file again or any TTMP with the same mod name.
3. Try and click the mod in Penumbra's list. 

Sometimes installing mods twice can happen by accident, especially when you have quite a few of them.

**Comment by Ottermandias** [comment]
Should be fixed?

**Comment by DevJinnial** [comment]
From what I was able to tell in testing @Ottermandias this has been fixed and can be closed.
