### ISSUE TITLE
Apply shared mount songs to character collection instead of base

### ISSUE THREAD

**Issue by Dinokin** [xivdev/Penumbra#355]
Currently, when a mod that changes the song of a mount is used, it needs to be applied to the base collection. Because of this, it does not sync with the mare (I assume).

The request is to change how songs for mounts, or shared mounts, are applied. Instead of being added to the base collection, they should be linked to the character data in a way that allows them to be synchronized with the mare.

Example of such mod: https://www.xivmodarchive.com/modid/49685

**Comment by Ottermandias** [comment]
Changing the redirected path of any SCD that is currently being streamed will straight-up crash you.
So all you would get here is "I can crash my friends when they hop on my shared mount", since Mare would not pre-load that SCD randomly.

**Comment by Dinokin** [comment]
@Ottermandias so the solution would be on mare's side or penumbra's side? or is it just an issue on how the client deal with SCDs?

**Comment by Ottermandias** [comment]
There would be no solution. We can not do this.

**Comment by Dinokin** [comment]
@Ottermandias A possible solution would involve loading either a dummy SCD or the stock SCD (obtained from a whitelist) until Mare finishes its process. Afterward, Penumbra could seamlessly redirect to the modded SCD without causing any crashes.

If it works i am willing to sink my head into it and do a PR but i need to ask ppl who know first before wasting my time XD

**Comment by Ottermandias** [comment]
No, this would not be a possible solution. This requires heavy reverse engineering to even associate the character with the song (potentially not even possible), and then you still have the issue that redirecting sound files crashes clients for Mare. BGM is not associated with your character, and will not be. Just drop it.
