### ISSUE TITLE
(Net5) Crash in resourceLoader

### ISSUE THREAD

**Issue by daemitus** [xivdev/Penumbra#36]
With zero mods installed:

https://imgur.com/a/hyt9hj3

Specifically as ResourceLoader.cs 190.

`var gameFsPath = Marshal.PtrToStringAnsi( new IntPtr( pFileDesc->ResourceHandle->FileName ) );`

**Comment by NotAdam** [comment]
@daemitus maybe try the build from the linked commit, might work? lol

**Comment by daemitus** [comment]
`var fsPathPtr = new IntPtr( &pFileDesc->ResourceHandle->FileName );`

**Comment by daemitus** [comment]
While this could technically be called some sort of regression, I think this is the appropriate behavior. FileName is a byte* and you try to read a pointer from it, so it reads a longlong's worth of ASCII and gives you a pointer. Where you actually wanted to & it.

**Comment by daemitus** [comment]
its a small string optimization.

```
    [StructLayout( LayoutKind.Explicit )]
    public unsafe struct ResourceHandle
    {
        [FieldOffset( 0x48 )]
        public byte* FileName;

        [FieldOffset( 0x58 )]
        public int FileNameLen;
    }
```

```
            string gameFsPath;
            var len = pFileDesc->ResourceHandle->FileNameLen;
            if( len > 15 )
            {
                gameFsPath = Dalamud.Memory.MemoryHelper.ReadString( new IntPtr( pFileDesc->ResourceHandle->FileName ), Encoding.ASCII, len );
            }
            else
            {
                gameFsPath = Dalamud.Memory.MemoryHelper.ReadString( new IntPtr( &pFileDesc->ResourceHandle->FileName ), Encoding.ASCII, len );
            }```
