### ISSUE TITLE
Mods no longer showing up on start screen? 

### ISSUE THREAD

**Issue by pommepom** [xivdev/Penumbra#374]
Hi! 

I recently had to reinstall my entire game, dalamud included, due to some computer issues. Upon doing so and reconfiguring all my mods, i realized that when I signed into the game, none of my mods showed on the startup screen. However, once I load in, they all appear again. 

Now, admittedly, this is a super small problem. They still appear in the game itself and they still function just fine - but it *is* jarring and I'm wondering if there is anything I can do to fix it? 

I've included some examples of what I mean below. Again, small problem - but annoying! Any help would be appreciated :) 

Start Screen: 
![ffxiv_dx11 2023-12-22 18-55-39](https://github.com/xivdev/Penumbra/assets/154648058/59cb9714-f5e3-4958-aec2-778a4eb0b9a4)

In game: 
![ffxiv_dx11 2023-12-22 18-54-43](https://github.com/xivdev/Penumbra/assets/154648058/889f1b01-cc8b-4f92-83b8-73bcbb287e16)

**Comment by Ottermandias** [comment]
Mods assigned to your character by name do not apply in the start screen. You can assign them to "Your Character" so they apply, or any of the fitting grouped assignments.
