### ISSUE TITLE
Model export error with faces

### ISSUE THREAD

**Issue by Gazzoo-byte** [xivdev/Penumbra#384]
Hi all, having a bit a trouble with the new model export feature, attempting to export any (I think, only tested Lalafell and Miqote) face gives the following error, the material is definitely part of the mod and in the active collection, though the path in the mod lacks the 'v0000' portion, not sure if that's the issue or if it's that the wrong slashes are being used as they're different also?

![image](https://github.com/xivdev/Penumbra/assets/73721238/05c715f3-bee9-419c-b9c5-38c0081f840a)

**Comment by ackwell** [comment]
thanks for the report! i can reproduce this.
it looks like the path resolution for face materials is erroneously including variants that don't actually exist (ref. the `v0000` in the path in your error).

i'll have a look into this
