### ISSUE TITLE
Character Collections Don't Work in GPose

### ISSUE THREAD

**Issue by DevJinnial** [xivdev/Penumbra#39]
So I'm not sure how on a technical level this can be fixed but once you enter gpose as of 0.4 any character specific collections are no longer applied. I assume this is just due to the lack of player names inside of gpose. Would it ever be possible for the collection to be retained or is this just a technical limitation that can't be bypassed

**Comment by Ottermandias** [comment]
I haven't looked into it very much, but I assume it's not fixable, at least not easily.
Gonna take a deeper look at it later, though.

**Comment by DevJinnial** [comment]
No worries! There is probably some identifier somewhere for it since you can remove party members or yourself but yeah I have zero idea where to even begin thinking about that. I'm not too terrible concerned about it but figured I would bring it up as I know a few people who would love this especially for trans mods.

**Comment by Ottermandias** [comment]
So, at least the player actor in GPose is actually a complete duplicate from your regular character in a different slot (your actual character gets hidden).
It's generally problematic though, since we don't seem to be able to redraw actors in GPose, at least not with the mechanism we use outside.

**Comment by DevJinnial** [comment]
Ooo interesting. I wonder if there would be a way to alter the duplicate before gpose drew the characters. Not sure that would really work though since it would have to intercept the character render before the screen loads

**Comment by Ottermandias** [comment]
Check 0.4.0.1 out, redrawing should now be possible in Gpose, and I think the playername-character collection should also work. I would assume that other character collections would have worked before already, but if they didn't I may need to look at calling the manual disable/enable draw on all actors if in gpose.

**Comment by DevJinnial** [comment]
Alright so a few notes after messing around a bit with it. I was able to run the command inside of gpose but it was a bit wonky.

- The redraw generates a new Non-Controlled PC and keeps PC Self the same
- This redraw doesn't seem to effect the existing PC Self
- Sometimes this new Non-Controlled PC will not have a model and will just be the weapons of the PC Self. When they do have a model, the gear is the correct player specific gear from the player collection.
- This new Non-Controlled PC can not be accessed via CM Tools or Anamnesis for pose editing nor can it be targeted in game
- If the redraw resulted in the new Non-Controlled PC model not being visible (only the weapons), upon exiting gpose the player model will also be invisible minus the weapons until another redraw occurs. 

I did not have someone with me to try this out with a party so all this is from just be by myself in the doman enclave. Lemme know if yo have any questions, I'll be online up until maintenance happens tonight. Feel free to add me on discord (`Khal#0001`) if ya need to reach me for testing

**Comment by DevJinnial** [comment]
@Ottermandias not sure at which update this was fixed since I haven't been on for several days but after updating to `0.4.1` it seems to be working perfectly now! Only thing of note is if you manually redraw inside of the gpose it will add a new entity with just the weapon visible. I am going to go ahead and close this now though.

**Comment by Ottermandias** [comment]
If you manually redraw what?
I'm pretty sure /penumbra redraw <me> or /penumbra redraw self does not do that. But /penumbra redraw [your name] might do it since it redraws your regular actor by name as well? (who is still there but hidden in gpose)

**Comment by DevJinnial** [comment]
Ahhh was not aware you could specify specific actors. It was adding an empty actor with just their weapon shown when I did `/penumbra redraw`. I believe the issue actual is just that it un-hid the regular actor you mentioned at the end there

**Comment by DevJinnial** [comment]
Alright so I am back with a bug for this @Ottermandias. Party members and other players do not have their character collections applied when entering gpose

**Comment by Ottermandias** [comment]
I guess I'll need to check for gpose and then go through the 48 gpose actor slots before I go through the rest of the actor list.
Thought other actors weren't copied in Gpose, but apparently at least group members and FC members are, maybe friends too.

**Comment by DevJinnial** [comment]
@Ottermandias alright the latest release fixed stuff. Only thing of note is when exiting gpose it seems the character collection is not re-applied to other characters and a redraw is required. I wasn't able to test but when I did a redraw it took about 5-10 seconds for the other player to redraw after me but that might have been the auto-redraw I'm not sure.
