### ISSUE TITLE
[Feature Request] API for automatic update mods from mod owner

### ISSUE THREAD

**Issue by justscribe** [xivdev/Penumbra#396]
Hi,
As title says, it's will be awesome to have such ability.
User can have some options to turn on\off auto update from the repository.

**Comment by MKhayle** [comment]
Hello,

You should probably look into [Heliosphere](https://heliosphere.app/) if you want to provide automatic updates to your mods. This kind of behaviour doesn't fall under penumbra's scope, to my knowledge.

**Comment by justscribe** [comment]
Oh, didn't know about this plugin. Thank you.
