### ISSUE TITLE
[Mod Support] Mod does not show up with penumbra

### ISSUE THREAD

**Issue by Tsunayoshi** [xivdev/Penumbra#407]
Hello,
i switched lately to penumbra and clean out my mods.
While doing this i noticed that this mod does not work with penumbra:
https://www.xivmodarchive.com/modid/46509

Any idea how to fix this? It change the target ring and its pretty useful as melee positionals.

Hope this can be fixed.

+1 since a friend use it also and have the same problem.

Edit; We only need Ring A but both did not work on testing.

**Comment by Theo-Asterio** [comment]
Mod support is done easiest in discord, tagging it [Mod Support] is meaningless. Highly suggest using it for troubleshooting it's much easier of a medium of communication. Past that you need to enable the above in your Base Collection, ensure wait for plugins to load at start is ticked in Penumbra and restart the game.

**Comment by Tsunayoshi** [comment]
Ah i will switch to Discord since it still does not work. But thanks for the advice!
