### ISSUE TITLE
Model exporter gives wrong vertex colors

### ISSUE THREAD

**Issue by ppartous** [xivdev/Penumbra#411]
The mod [Neo-Ishgardian_Top_of_Fending_TGT_1.2.ttmp2.zip](https://github.com/xivdev/Penumbra/files/14828909/Neo-Ishgardian_Top_of_Fending_TGT_1.2.ttmp2.zip) normally looks like this

<img src='https://github.com/xivdev/Penumbra/assets/32884861/95ab65ec-0a90-4f68-a1bf-a4c7fc918170' width='350'>

But if I export it with penumbra and then import it again without making any modifications to it, it now looks like this

<img src='https://github.com/xivdev/Penumbra/assets/32884861/6df893e5-eb62-4d63-9a26-41cb7697230c' width='350'>

If I export with textools then use blender to convert to gltf and import with penumbra it looks normal so it breaks during exporting.
Looking at the vertex colors in blender, the model exported from penumbra has the color #FF0101 on the areas that are broken

<img src='https://github.com/xivdev/Penumbra/assets/32884861/062e148b-8c2b-474d-bab0-966872532578' width='350'>

Whereas the model exported from textools has #FFC864

<img src='https://github.com/xivdev/Penumbra/assets/32884861/6e43b1fd-c473-45af-aa93-d3e306b6c865' width='350'>

I'm using penumbra version 1.0.1.0

**Comment by ackwell** [comment]
Ah, I wasn't normalising the color values. Will be fixed with next batch of fixes.

**Comment by sprocketaudio** [comment]
Hi, has this fix been pushed to live yet? I want to test a similar issue i reported a while back on discord

https://discord.com/channels/884363610640498698/1221513268879818752

**Comment by ackwell** [comment]
No. This issue will automatically be closed once the fix is merged.
If you want to check, you can run a dev build on this branch: https://github.com/xivdev/Penumbra/compare/master...ackwell:Penumbra:mdl-io-triage-6
