### ISSUE TITLE
Base collection setting is enabled for everyone (resolved)

### ISSUE THREAD

**Issue by Loveless33** [xivdev/Penumbra#413]
I have my collection set to myself but recently I have noticed that anytime I use anything that falls under Base (minions, mounts, etc) are applying to everyone. This is particularly a problem with prop mods since they take up such a large space often and can end up in the way. I can turn off Base in collections but then I won't see my own minions and such changed. As I never seen this happen previously I am putting it here.

**Comment by Theo-Asterio** [comment]
This isn't a bug, this is not understanding how collections work, you can enable minions/mounts in your own collection and not put it on Base. Base Collection applies to everyone else not specified elsewhere to have a collection assignment and always has. 

Tick Use Ownership on the Penumbra settings tab and you can make it so minions/mounts/etc can be enabled in your own collection and affect your own minions/mounts/etc. 

Highly recommend you use the discord for support so it's easier to see your collections and help for future reference.

**Comment by Loveless33** [comment]
Ohh thank you for the information! I will do that in the future <3
