### ISSUE TITLE
Model export exception: "Mesh 1: Unexpected UV vertex type Single2."

### ISSUE THREAD

**Issue by iCatz** [xivdev/Penumbra#416]
Hello there!

I have been working on a model/mod recently and I have been editing the model in blender, but when trying to export the .mdl as a gLTF again, it gives me an exception about what looks like the skin mesh. So I'm not sure if this is something i've done wrong on my end and if it's fixable. Thank you for your time!

![a512790a4679d9547383f4cabd5206f8](https://github.com/xivdev/Penumbra/assets/5912050/6548f006-c733-44a7-93ff-d0b19d9be96c)

**Comment by ackwell** [comment]
Known issue, fix is merged and will be in the next release when it comes out.

For now, if you're working in blender, I'd recommend just keeping your changes in blender and just using import to test. There's no need to re-export from penumbra each time (a round trip through xiv MDL format is technically lossy).

If for some reason you feel you absolutely must round trip through MDL, you can ensure that your models have two UV maps to avoid this error until the next release.
