### ISSUE TITLE
Search for 'Changed Item'

### ISSUE THREAD

**Issue by Gabbalo** [xivdev/Penumbra#419]
I really would like a feature not only to search for mods by name oder for the items that are currently changed or on screen, but also for the items, that can be changed, even by disabled mods.
And the reason is very simple. I often safe designs in Glamourer but happen to disable the corresponding mods (without having them linked to that design, yeah, yeah, I know ...). 
Now I have that design and the only thing I can look for is the item that I would have changed by it. By now, I can't, if not looking at every of my maaaanyyyyy mods manually.

Since that information is safed for every item anyways I hope it might be just a frontend change for the search mask and nothing too complicated in the background.

**Comment by Ottermandias** [comment]
![image](https://github.com/xivdev/Penumbra/assets/70807659/0feee902-bec6-4a94-8fe5-63e2e803b5ea)
