### ISSUE TITLE
Installed mod list UI requests

### ISSUE THREAD

**Issue by PrincessRTFM** [xivdev/Penumbra#42]
In the installed mods list, can the sidebar showing the tree of mods be widened for long names? Some mods, like gear changes, have their title but also the body mods they're designed for.

Can mod names be indented under their folder groups for better alignment? For example, in the image below, the mod names under my `Minion` folder are left-aligned with the arrow. However, the subfolders are indented further right, which nicely represents the heirarchy.

Would it be possible to sort subfolders above mods? Windows explorer does this by default IIRC, as an example. Folders sort alphabetically but all display above normal files.

![](https://i.imgur.com/i57o55R.png)

**Comment by Ottermandias** [comment]
1. Sure, but that takes space away from the mod panel. I could probably do a scrollbar, but I'd recommend renaming overly long mod names instead.
2. I'll look at indentation depth, should be no problem.
3. Nope, not for now. This is not an actual folder structure, I do not introduce any objects for folders (i.e. I don't have any tree-like structure). I iterate through the alphabetically sorted list and introduce a folder whenever a new / appears and close it when the next file doesn't begin with the same prefix. You can do this manually though, by changing the sort-order of the files you want below mods to be... well, below mods :D

**Comment by Ottermandias** [comment]
1. The selector now has a horizontal scrollbar if necessary, and there is an option to let it scale with window width (i.e. it stays proportionally the same compared to the total window).
2. I increased indentation depth by 2.5 pixels to 12.5, which appears to be the exact center of the triangle, this seems to be good enough in any case :D

**Comment by PrincessRTFM** [comment]
Awesome, ty!
