### ISSUE TITLE
[Feature Request] Transitive relationship/chaining for file redirections

### ISSUE THREAD

**Issue by melroy999** [xivdev/Penumbra#424]
Would it be possible to have file redirections and file swaps behave like a transitive relation? To exemplify, suppose we have the redirections (a -> b) and (b -> c): through transitivity path a would then be redirected to path c, instead of b.

The latter would allow for the options chosen within one option group to directly affect the behavior of options in a successor option group by including a set of intermediary file swaps. One could for example provide option groups that independently characterize the desired looks of a skin (base skin, freckles, tattoos, aura scales, etc.) and have the appropriate texture be selected by chaining the file swaps defined by the selected options. 

A major benefit of this feature is that the number of options per option group can be kept more manageable while still providing the same level of customization, which in turn results in a cleaner looking mod with more intuitive configuration options.

**Comment by Ottermandias** [comment]
No.

**Comment by Ottermandias** [comment]
No worries. You haven't wasted my time. It's just not feasible.

**Comment by melroy999** [comment]
Ah right! Sorry, the concise answer gave me the false impression you were irritated, so sorry for having jumped to conclusions. (Then again, it wouldn’t be a surprise given that Dawntrail is at the doorstep, you likely have a lot on your mind already!)

Admittedly, I did experiment a bit myself out of curiosity prior to creating the feature request and came up with a draft implementation that seems to work on my end. From what I can gather, the desired behavior can be implemented entirely within the scope of the GetData method of the Mod class (by postprocessing the dictRedirections dictionary). 

However, I am not sure whether changes need to be made elsewhere in the plugin for internal/external mechanisms that I might be unaware of, or whether the performance impact will be within acceptable margins—are the feasibility concerns originating from there?

Either way, I can attempt to create a more robust implementation and share it here/create a pull request if you consider it worthwhile, or just drop the matter entirely if preferable.

**Comment by Ottermandias** [comment]
Did you consider all situations here? Like the initial redirection turning off while the second redirection stays? We need to be able to revert and deal with conflicts.
If you think you can implement that robustly and in an intuitive and sane way that can be communicated and explained to users without any surprises, sure, feel free to create a PR.
As long as you're also okay with that effort going "to waste" if I decide I do not like your solution, at least. I really don't like discarding people's effort.
(This is not meant to imply that it's likely that I'd discard it or anything, just pre-emptive)
Something like this was requested a bunch of times. I'm of the opinion that it creates more ugly situations and problems than it solves, but maybe you can show me that I'm wrong. :)

Regaring the "options per option group", I already intend to create Combining groups (in the sense that it's a multi-select group but every combination of options has their own data for the mod creator to define, i.e. 2^N data containers for N options) and maybe later on extended groups, where option availability could depend on the entire settings.

**Comment by Ottermandias** [comment]
Also regarding the terseness: it's a) a knee-jerk reaction I tend to (it's very rare that there's a bigger functionality suggestion I haven't already thought about in some way, so I usually have considered a lot more issues with it than the person making the suggestion), and b) kind of a catchphrase by now :D
