### ISSUE TITLE
Unable to Receive Updates

### ISSUE THREAD

**Issue by Oliviaphe** [xivdev/Penumbra#434]
I haven't been receiving update notifications for Penumbra. It's still on version 1.1.1.2. 
I've checked my repository link, and there are no errors, but I'm still not getting any update notifications.
It has been ongoing for a long time.

**Comment by DenowRammy** [comment]
If you cannot get the testing branch to work on your own, you should not be using it. Support will not be available at this time for testing installation, including updating.
