### ISSUE TITLE
Animations bugs with Penumbra

### ISSUE THREAD

**Issue by XiKav** [xivdev/Penumbra#436]
When i use Penumbra, during Boss fights... a lot of their animations are just like.... canceled... (adds included). Most of the time, it does really matter, as the fight is still doable, in some way... but during the fight against Shinryu, for example, after you're brought to the second phase, the animations are canceled or works weirdly, making the boss doing some things that is not supposed to do... and you get "stunned" during all the flight until the "second plateform" flight supposed to be skipped via the cinematic... kinda...

**Comment by Theo-Asterio** [comment]
If you're for some reason on 1.2.0.13 update your plugin and do not manually install plugins either.

**Comment by XiKav** [comment]
> Try assigning the "Use No Mods" collection to everyone, while keeping the "Enable Mods" on, and then restarting your game, and retrying these fights.
> 
> If the issue persists after doing that, it means that it is indeed a Penumbra issue, otherwise it is an issue with one of your mods.

Tried your thing : "use no mobs" for everyone (me included) => restart the game => try a fight where the problem is easily visible => the issue persists.

**Comment by Theo-Asterio** [comment]
> Tried your thing : "use no mods" for everyone (me included) => restart the game => try a fight where the problem is easily visible => the issue persists.
Then what version of penumbra are you on, also have you considered using the discord for support for quicker answers and would allow people to see the support info way easier.

**Comment by XiKav** [comment]
> Then what version of penumbra are you on, also have you considered using the discord for support for quicker answers and would allow people to see the support info way easier.

hey, well, you'll laught at it... 1.2.0.13...

**Comment by Theo-Asterio** [comment]
Stop manually installing the testing version. You're on the very version that was banned from dalamud due to issues. Manual install = no updates, please learn how to use the testing version on the dalamud installer or don't use testing.

**Comment by XiKav** [comment]
not forced to be aggressive either... at least i know where the problem came from... if it came help other people that MIGHT share the same problem. If i use the test version, it's because the official one is still outdated, Needless to say, waiting is not one of my best qualities.

anyway, had tested the new version, seem to work.
