### ISSUE TITLE
Missing apply body textures button for bibo+ to mod

### ISSUE THREAD

**Issue by livvydoodlez** [xivdev/Penumbra#437]
There use to be a button on the edit mod tab that allows you to apply your bibo+ skin to the mod, and in version 1.2.0.17 testing, it has been removed, so there is no way for me to apply my bibo+ textures to the mods anymore :(

**Comment by Caraxi** [comment]
You misunderstood what what button did

**Comment by livvydoodlez** [comment]
It worked fine for me?

I use two bibo+ body types, and so far, every mod that I'm using worked great (even with the new DT updates), and it would apply the right textures exactly as they are.


Now the only way to get the mod skin to match my actual body is to manually replace the textures...

**Comment by ezudo** [comment]
All that button did was change bibo+ bodytexture paths to the updated versions, for mods that dated back to pre-bibo2.0 afaik. The mods should just pull the bodytexture from your currently active Bibo variant/tattoo mod.

**Comment by livvydoodlez** [comment]
Unfortunately some dont, but now with the button gone at all, I can't do it at all unless I manually replace the texture by going into the directory and over-writing the old texture file... which is not ideal if I'm using different textures for each bibo+ body.

**Comment by Theo-Asterio** [comment]
Use the material reassignment button in advanced editing, why have you not tried checking there first before trying something tedious? Reniguide also has the list of what legacy bibo materials went by. Also it “working for you” doesn’t mean anything when people clicked it willy nilly and you don’t seem to fully get what it did do. 

People used to click it on gen 3 mods, breaking them entirely thinking it just magically assigned it to bibo. People clicked it on everything assuming it turned anything bibo.

If you aren’t comfortable enough to use advanced editing I suggest not being on testing.

**Comment by livvydoodlez** [comment]
Wow.

Like get off your high horse? Why do you have to be so rude? I've literally always used the assign bibo material button for all the mods I used and it worked. It's something I got comfortable with.

All the guides associated with mod packs, a lot of them state to even use the button to fix your skin tone to the material. Like I don't see why you have to give such an attitude and be an asshole about something so trivial as asking why the button was removed, and asking for a way to bring it back or to use it another way.

Like if you aren't going to supply anything helpful and just be a prick, I suggest just not replying to my thread, or any thread for that matter.
