### ISSUE TITLE
Race-specific changes

### ISSUE THREAD

**Issue by steponmepls** [xivdev/Penumbra#44]
Are there any plans to force mods to work only with certain races (and/or genders)? For example, [this one mod](https://www.xivmodarchive.com/modid/7694) affects the `Werewolf Head` item but at the same time it breaks it on every other race. The owner offers two variants, one that works in normal TexTools (and that I am currently using in Penumbra) and one that works in a [patched TexTools](https://github.com/esrinzou/FFXIV_TexTools_UI) fork "which adds a Lala specific material".

![image](https://user-images.githubusercontent.com/63500907/127888994-7f443f82-ad4b-4de3-8371-848d4b8592a1.png)

**Comment by steponmepls** [comment]
I understand. Would this be simply too much work to implement considering you can fix the issue in the mod files itself? There might be other use cases like forcing a model change only on your character and using the vanilla ones on the rest.  I don't fully understand what you technically can or can't do with Dalamud so I'm just wondering if this is an issue you can't forcefully fix in Penumbra itself with mod specific configs or if simply this is a very low priority issue that could be easily fixed by editing the mod itself instead

**Comment by Ottermandias** [comment]
Penumbra has absolutely no idea for what reason a file is loaded, or what kind of file it is, so stuff like this is simply not possible in Penumbra, sorry.
The 'other case' is basically possible, using character collections I implemented thar are hacked together by letting penumbra actively reload those players when necessary and changing the loaded files until that player is reloaded, but that's terribly hacky.

I'll close this issue now.
