### ISSUE TITLE
Penumbra library keeps resetting. 

### ISSUE THREAD

**Issue by NationFive** [xivdev/Penumbra#451]
I have no idea how to replicate the bug, I spend either an hour or two I enter a different instance and then my library completely resets by either making all the mods I installed disappear or most of them.

I install them again and it disappears once more. What could be causing the problem?

**Comment by Theo-Asterio** [comment]
Having your root directory for penumbra be in an awful place. Onedrive not recommended, external hard drive not recommended.

**Comment by NationFive** [comment]
Hey Theo, my root directory isn't in either. When it first happened I was using my old destination folder, after I updated it happened again. So far it's happened once after I updated it but I am trying to figure out what would cause it.

**Comment by Theo-Asterio** [comment]
Permissions, antivirus, anything could be the reason. Hardware could likely be the other issue. Your drive having read/write issues. You're not really providing much to work on such as location. Can't replicate this either on any good locations.

Don't run ffxiv as an admin either if you have been.

**Comment by NationFive** [comment]
It's all located in the C drive in an SSD but so from the looks of it there is a chance it's a hardware malfunction is what you're suggesting?

**Comment by NationFive** [comment]
Mostly my old file was in C and the new file is in the C file, I don't know what kind of information you need as I am not quite tech savvy myself and I apologize for my ignorance for that matter but if there is anything I can throw out there to help I'm more then willing to share information.

**Comment by Theo-Asterio** [comment]
Yes, there's a high chance it's hardware but this isn't the avenue for general tech support.

**Comment by NationFive** [comment]
Gotcha, thanks for helping me identify the problem, have a great evening!
