### ISSUE TITLE
Can't get Penumbra to stop showing Halloween cosmetics

### ISSUE THREAD

**Issue by SariahPendragon** [xivdev/Penumbra#456]
I can't for the life of me find a setting that stops this.  It showed a prompt asking if I wanted to try some Halloween cosmetics, hit yes, and now I can't figure out how to get it to stop. It chooses a random override on every login, and a random color.  I've disabled all mods and it still does this.

**Comment by Theo-Asterio** [comment]
Not penumbra, Glamourer. Stop opting into festivals if you don't want to see festivals like this. It's under settings.

**Comment by SariahPendragon** [comment]
> Not penumbra, Glamourer. Stop opting into festivals if you don't want to see festivals like this. It's under settings.

Thanks. I'd just figured it out as you commented this.
