### ISSUE TITLE
Some cutscenes break with Character Collections

### ISSUE THREAD

**Issue by BSoD38** [xivdev/Penumbra#46]
This is a relatively minor issue, but when using character collections on the player character, some minor cutscenes break.

Cutscenes such as waking up from the bed when logging in from an inn breaks: instead of waking up, the character will already be up besides the bed, and nothing will happen for a few seconds, before returning to normal gameplay.

I've seen another instance of this issue happening elsewhere, where the character had an idle animation instead of doing something, but I forgot where, sadly.

I'll try to see if this problem happens consistently or not next time I'll log in.

**Comment by Ottermandias** [comment]
Yeah, an actor reload removes current animations. I could probably prohibit reloading during cutscenes, but then you'll not have your custom settings in them. Maybe make it a setting.

**Comment by Ottermandias** [comment]
This probably only matters when you enter a cutscene directly from a loading screen, so I just generally do not reload during cutscenes now.
