### ISSUE TITLE
Penumbra shows mods installed but they aren’t drawn.

### ISSUE THREAD

**Issue by theantichris** [xivdev/Penumbra#460]
I got a new PC setup today and installed everything. I copied my old FFXIVMods folder to the new computer. All my mods show they are installed and enabled but none are being drawn.

**Comment by Theo-Asterio** [comment]
Yes, you didn't copy over the actual configs. Highly suggest using the discord as it has an faq on all the information such as migration instead of here.

**Comment by Theo-Asterio** [comment]
Then if it's not working you didn't put the configs where they need to be on your computer but, you're neither showing any evidence or are in an easy vein to do this kind of support.

**Comment by theantichris** [comment]
I apologize, I am not trying to be difficult. From what I can see I have everything where it needs to be according to the documents. I'm sure I could have missed something but can't seem to find what it is.

Here are my Penumbra settings.

![Penumbra settings](https://github.com/user-attachments/assets/f6e0d6ff-2725-4e3c-bc31-8af7fc10278f)

Here is the Penumbra mods tab.

![Penumbra mods](https://github.com/user-attachments/assets/5c65d6ea-f01a-49b6-bf06-05fce9ec1d3e)

Here is my plugins configs folder.

![pluginConfigs folder](https://github.com/user-attachments/assets/843e4276-af67-4971-b1c8-54371bd2b5ca)

Here is the Penumbra mods folder.

![Penumbra folder](https://github.com/user-attachments/assets/1bf34dd0-919d-4b03-b91d-180e4b565af2)

And here is the FFXIV mods folder.

![FFXIVMods folder](https://github.com/user-attachments/assets/7b81cac2-8d48-4414-86b7-b68da33073c1)

**Comment by Ottermandias** [comment]
Can you show us a) your actual collection setup in the collections tab, and b) what files are in, e.g., the Thavnairian bustier set mod. Like, right click on it and show how many / large files there are in total and show the content of the main folder.

**Comment by theantichris** [comment]
Here is my collections tab.

![Collections tab](https://github.com/user-attachments/assets/68d2f25e-b843-4ec7-9af0-b05215bd238d)

I'm not sure what you're asking me to right click and see but here is a shot of the contents of the mod's folder.

![Thavnairian bustier folder](https://github.com/user-attachments/assets/c9089f3d-6fbd-437b-af8a-a8e5d2caae6a)

**Comment by Ottermandias** [comment]
I'm asking for an actual file count inside the mod. We had pretty frequent cases of people migrating their mods and either the explorer or windows or a cloud sync tool messing this up and not actually copying the mod files, only the folder structure.
(i.e. I want to see if the subfolders of this actually do contain .tex and .mdl files etc. - they might be empty due to aforementioned issues)

**Comment by theantichris** [comment]
Is this what you're looking for then?

![Thavnairian bustier folder properties](https://github.com/user-attachments/assets/a97d6e42-b446-4dd1-a32e-4cbeb606b48f)

**Comment by Ottermandias** [comment]
Yes. There are 12 files of 2.7 MB in this folder, which are exactly those 12 .json files we can see in your above screenshot.
This means, that there is not a single modded file in it, only the metadata for Penumbra. Your copy-process somehow skipped the actual data files entirely.

**Comment by theantichris** [comment]
I appreciate the help. I'll just reinstall everything. Have a great day!
