### ISSUE TITLE
Mod groups (in a more user friendly way than collections)

### ISSUE THREAD

**Issue by JoelZimmerman** [xivdev/Penumbra#47]
So while collections are a step in the right direction, it would be nice to have an easier and faster way to enable and disable certain groups of mods that doesn't involve having to make a ton of collections and painstakingly modify them when you swap around old mods/add new ones, etc. I've attached a quick mockup to make it easier to visualize the feature.

* Having a checkbox in each dropdown group makes it fast and convenient to enable and disable them. Other than the checkbox on the dropdown group itself, most other stuff would remain untouched.
* Drag and drop for adding/removing items from groups, again for convenience.
* When you add new mods it could just put it straight into the unsorted dropdown which you could have disabled as default, the same way as it is now.

![image](https://user-images.githubusercontent.com/30196396/128410986-37f86553-3752-4b93-8cd8-686004760d5c.png)

Hopefully something like this could be considered for a future release.

**Comment by Kylis** [comment]
I second this. My list is getting rather unwieldy and would love to have the ability to organize things like this!

**Comment by Ottermandias** [comment]
You are aware that mod folders (including subfolders) are a thing, you can drag and drop mods between them (including the folders themselves) and you can right click them to enable or disable all of their descendants at once... since like... June? Before the issue was even opened?

**Comment by lmcintyre** [comment]
To be fair, the right click is not very intuitive - I had to ask if this functionality existed. While I think the functionality is sufficient, discoverability could be improved.

**Comment by Ottermandias** [comment]
I mean, I don't disagree, but "right click for context menu" isn't that far-fetched to figure out yourself.

**Comment by eaganlai** [comment]
> You are aware that mod folders (including subfolders) are a thing, you can drag and drop mods between them (including the folders themselves) and you can right click them to enable or disable all of their descendants at once... since like... June? Before the issue was even opened?

May I ask how to create mod folders? I tried right-clicking the mods and the "add" button at the end of the list. Is it anyway related to the "collection" tab?

**Comment by SerenitySunfire** [comment]
> 

You right click a mod, and type the folder structure you want. SO say you have a mod called Sweater, and you want to put it in a folder called Clothes. You would right click the mod, and type Clothes/ prior to the Sweater mod name. So, once you are done, the folder structure would be Clothes/Sweater.

**Comment by eaganlai** [comment]
Thanks for the guide. Kudos to you, sir!

**Comment by SerenitySunfire** [comment]
> Thanks for the guide. Kudos to you, sir!

Ma'am, but you are welcome.
