### ISSUE TITLE
Modpack fails to import

### ISSUE THREAD

**Issue by Aida-Enna** [xivdev/Penumbra#48]
This single file out of 13 skill replacement files does not import into Penumbra. Creating ticket per ingame UI ("One or more of your modpacks failed to import. Please submit a bug report."). I have Penumbra configured and working correctly with a ton of other mods. Below is the ttmp2 file, zipped.

[Maim【新凶残裂fix】.zip](https://github.com/xivdev/Penumbra/files/6966819/Maim.fix.zip)

**Comment by Ottermandias** [comment]
Are their names purely in the same number of Kanji, i.e. are their folder names replaced to the same number of underscores?
The number 13 is pretty relevant because `while( newModFolder.Exists && i < 12 )` :D

**Comment by Aida-Enna** [comment]
Yes, that's probably the issue then lol

![image](https://user-images.githubusercontent.com/5483362/129028890-8ed258b2-3d96-4721-b25e-3e131dd5cfd1.png)

**Comment by Ottermandias** [comment]
I pushed a change that displays the error message on failure to import, so if this happens again or to other people they should be able to fix it themselves.
I don't want to remove a numeric restriction to the creation of folders because I think that would be bad practice.
