### ISSUE TITLE
Missing textures on certain mods. 

### ISSUE THREAD

**Issue by SneakyBelg** [xivdev/Penumbra#52]
Tail mod that works perfectly fine has missing and translucent textures when using a penumbra character collection. 
Importing it into default works perfectly, however using a character collection makes textures go missing.

**Comment by Ottermandias** [comment]
Yes, files that are not reloaded on redrawing do not work with character collections.
If it is a file that generally works with manual redrawing after disabling/enabling it and then not restarting, please state what version you're on and provide the file.

**Comment by SneakyBelg** [comment]
Yeah it generally works when in default or in textools itself. Tried beforehand with manual redrawing after enabling and disabling. Character collection doesn't load it, i'm guessing due to it not picking up all character data maybe?

File i'm trying to use: https://www.xivmodarchive.com/modid/7911

**Comment by SneakyBelg** [comment]
Just came back from afk'ing for an hour. Didnt exit game didnt click a single button just afk. Tail mod seems to have fixed itself and the missing textures have been added in. No clue how it's possible though
