### ISSUE TITLE
"Log cull threw an exception; being used by another process"

### ISSUE THREAD

**Issue by jupiknight** [xivdev/Penumbra#56]
So I've been using Penumbra for a while now, and I often dual-box my two accounts at once. Since the XIV update, I've been getting this error:
![anotherprocess](https://user-images.githubusercontent.com/74471934/136662996-4a49243a-1346-473c-8ee1-a9dbe38527bd.png)
It doesn't seem to actually cause an issue, but I just wanted to point it out. I haven't added any mods or stress tested it, but it seems it's probably a niche issue, since most people probably don't dual-box two instances of the game at once.

**Comment by Ottermandias** [comment]
It has nothing to do with Penumbra, but Dalamud proper.
