### ISSUE TITLE
Scale mods don't play nice - caching issue?

### ISSUE THREAD

**Issue by Naixatloz** [xivdev/Penumbra#59]
I'm trying to set things up so that all female Au Ra use one scale mod by default, but my character collection for a specific alt uses a different one. My understanding is that this should affect only my character while leaving all other femra untouched. However, what seems to be actually happening is the following:

Body - Always the scale set used in the default collection, even for my own character
Head and tail - All femra with my character's face and/or tail type use the character collection scales, all others use default collection scales

Redrawing doesn't fix this whatsoever. In fact, redrawing has never affected scale mods in any version of Penumbra I've ever used. If I disable both these scale mods and redraw, nothing changes. (This has also been the case for the tattoo mods I've tried for my elezen, but that's less of a priority for me personally.)

![default](https://user-images.githubusercontent.com/92188768/136762565-b93427f6-1636-4823-99e8-f61e42b1d2cb.png)
Relevant mods in my default collection.

![collection](https://user-images.githubusercontent.com/92188768/136762617-e746023b-530b-4657-a516-2bc14f68cd67.png)
Relevant mods in my character collection. In both collections, enabled mods are shown in descending priority.

![2021-10-11_02-03-40-009_Shadowbringers Custom](https://user-images.githubusercontent.com/92188768/136763492-1b084a31-4dc0-4f2a-ba0c-27a61694d27c.png)
Probably not relevant, but including for the sake of completeness - file conflict that only exists for Sin Eater Raen mod involves the body scales.

![2021-10-11_01-41-47-636_Shadowbringers Custom](https://user-images.githubusercontent.com/92188768/136763143-84ac9973-b4df-47f2-b09e-6d5c55d9a103.png)
![2021-10-11_01-45-12-131_Shadowbringers Custom](https://user-images.githubusercontent.com/92188768/136763306-74e1d2da-1721-4b00-bcbf-45b70425e027.png)
Examples of issue.

**Comment by SoeyKitten** [comment]
> They do not get re-requested by the game on redraw and thus require a restart of the game to apply

I pretty much have the same issue, in my case it's the black sclera that I just wanted to apply to *some* characters, and would always show white in more crowded locations / when other chars are present with the same eyes. Simple redrawns don't work, as you said, but they do seem to be re-requested on teleport though, like when I leave an apartment and reenter it for example, not just on restarts. Maybe that info helps?

Would be amazing if that could be fixed somehow, cause being able to mod characters individually is a pretty huge deal imho.

**Comment by Shuraen** [comment]
I'm having the same issue as of this date.
I'm using specific scale mods for a character with Face 3 but they're applied to the same faces of random strangers when I'm on that character.
