### ISSUE TITLE
[Enhancement] "My Characters" Collection / Applying collections to retainers

### ISSUE THREAD

**Issue by Diorik** [xivdev/Penumbra#68]
Root cause of this request is I want a way to apply a collection to my retainers beyond forced/default and named collections can't do that. In general I think it's very common for people to list their own characters in specific collections and both problems could be solved in one feature.

A new built in collection "My Characters" that always targets the active player character and if possible, also applies to retainers when they are loaded in. Additionally, if possible, "My Characters" collection mods could be implicitly applied at the character select screen over Default/Forced.

**Comment by Ottermandias** [comment]
Why can't named collections do that?
And you could just use the same collection for all those names? I don't understand what's missing here.

**Comment by Diorik** [comment]
Ah, it looks like there's a bug that prevented named collections from working on the one retainer I tried this on. A single hyphenated word like "First-last" is a valid retainer name that doesn't seem be caught by Penumbra for collections. I can write a separate issue for that if desired.

I edited my original post but the appeal to "My Characters" is really just some QoL beyond that, instead of manually defining each of my alts and retainers or seeing wrong mods at the character select screen.

**Comment by Diorik** [comment]
Just to re-iterate the use case on a "My Characters" category this one more time after playing for a while. If you're not convinced (or it's not functionally plausible) go ahead and close this since it's just the bug with my retainer name that caused the original issue.

I've been using "Forced" as a baseline for all characters, "Default" as an override for randos, and the named collections to make overrides for my characters and retainers. What's happened is that in all cinematics, paper doll, and character select, none of named collection mods apply to my character. It's hardly the end of the world, but assuming you can detect these situations in Dalamud, the upside of "My Characters" is that you can make some assumptions even when there's no name: Paper doll and character select - obviously mine. A player character in a cutscene? Probably mine - false positives will occur, but I'd personally opt into false positives over all the false negatives.

"My Characters" would basically be the opposite of Default - anything specifically named or otherwise implicitly "mine" receives My Character collection mods. Default covers everything else, both sets override Forced.

**Comment by Diorik** [comment]
Closing this for being a sprawling mess, will write separate bug for hyphenated name issue.
