### ISSUE TITLE
Mods no longer enable or disable

### ISSUE THREAD

**Issue by Deltaforce229** [xivdev/Penumbra#69]
A couple days ago I noticed mods stopped disabling. The UI would update to show the mods disabled but would not actually change what was in the "Effective Changes" tab. I left it alone and came back to it today. I've tried completely deleting Penumbra with exception to the folder containing the mods and reinstalling. After rediscovering the mods folder none of the mods will enable. The UI shows them enabling but again nothing changes under "Effective Changes". Once again I deleted and reinstalled Penumbra, this time attempting to import a single ttmp2 file. Again the UI shows the mod enabled but nothing happens under "Effective Changes".

**Comment by Ottermandias** [comment]
Have you a Current Collection that's not set as the Default or Forced Collection?

**Comment by Ottermandias** [comment]
If you enable something in a collection that's not set as the current Default collection, it will not have any effect.
You just have new settings for a different collection that is not used. 
That is not a problem, that is all working as intended.

**Comment by Deltaforce229** [comment]
I think I understand now. "Current Collection" is for editing and "Default Collection" is the collection currently being used. I think that I may have set my Default collection to None after deleting my collections. Although I'm not sure why issues continued to persist after reinstalling and not messing with collections. Either way I apologies for taking up your time, hopefully this serves to help someone else.
