### ISSUE TITLE
Unable to install penumbra anymore

### ISSUE THREAD

**Issue by Myakko** [xivdev/Penumbra#74]
Hello !

After starting over my textools (which I've done multiple time by the past), penumbra didn't show up in my plugins.

I deleted it from the xivLauncher folder, and tried to install it with the repo url, without success.

Error in the log says : System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.

[PenumbraLog.txt](https://github.com/xivdev/Penumbra/files/7559747/PenumbraLog.txt)

I also tried to install it the old way (pasting the code in dev plugin), without more success.

**Comment by Myakko** [comment]
More infos

Apparently, it's something with a mod I installed.

Removing penumbra collection and config enabled me to install it again.

But when trying to put back my penumbra mod folder, the plugin crashed.

I will have to track it down or start from scratch I guess !

**Comment by Ottermandias** [comment]
It probably tries to add a new variant, which is not supported at the moment. It shouldn't crash due to that of course, and it's probably fixed on my local build, but not pushed to release yet.
