### ISSUE TITLE
Separate default collections for players and NPCs?

### ISSUE THREAD

**Issue by PrincessRTFM** [xivdev/Penumbra#75]
Would it be possible/feasible to allow setting a default collection for _NPC_ models that's separate from the player/general default? For example, I have a couple of mods that I like on NPCs, but I would prefer to not be changing player outfits as radically as these mods do, since players can mix and match their clothing. If there were a way to separate out the two - a default for players and a default for everything that's not a player (including UI/VFX mods) for instance - then I'd be able to freely adjust default NPC outfits without messing up player glamours.

**Comment by DevJinnial** [comment]
I'm pretty sure you can just do that via a character collection for their textures and models. Like I have one for Graha with a few different mods just for him

**Comment by PrincessRTFM** [comment]
That's a totally different thing though. That affects a single NPC by name. I'm asking for the ability to affect all NPCs _and only NPCs_, by default, unless overridden by a named collection.

**Comment by Ottermandias** [comment]
No.
