### ISSUE TITLE
Not Working 

### ISSUE THREAD

**Issue by Twilight-Wolfy** [xivdev/Penumbra#80]
im trying to get Penumbra working in the most recent version of FFXIV but i can't get it working i tried updating my penumbra downloading the latest files and adding them to the right folder on my PC but no luck can you help me please?

**Comment by dovochi** [comment]
It hasn't been updated for Endwalker yet. We'll have to wait for a new version before it can work again.

**Comment by lorenzobar** [comment]
> It hasn't been updated for Endwalker yet. We'll have to wait for a new version before it can work again. Dalamud has been updated already though so several other plugins are now working. From this point on I recommend completely removing Penumbra from the devPlugins folder and use the custom repository link below to install and keep Penumbra updated through Dalamud instead. You can enter the link by typing /xlplugins in chat, then click Settings -> Experimental. Click Save after you enter the link. https://raw.githubusercontent.com/xivdev/Penumbra/master/repo.json

Hi, once i put the link, how can i see penumbra from the list of plugins in dalamud? it isn't showing, not even with an error

**Comment by dovochi** [comment]
Once you click the Save button, Penumbra should show up on the list of
available plugins that you can install. You might not be able to see it on
that list yet since it's still haven't been updated and because Damamid
automatically disables all outdated plugins by default upon login.

2021年12月9日(木) 15:35 lorenzobar ***@***.***>:

**Comment by Twilight-Wolfy** [comment]
Thank you so much for the info I'll try it once I get home

**Comment by Twilight-Wolfy** [comment]
So i added your link then tried to search for the plugin and its not coming up sadly ill wait for a new release of Penumbra
