### ISSUE TITLE
Male Viera support

### ISSUE THREAD

**Issue by Sevii77** [xivdev/Penumbra#81]
Male viera is currently not supported as it needs to be added to `Penumbra.GameData/Enums/Race.cs` (maby other places aswell, haven't really checked)

**Comment by Ottermandias** [comment]
That's just for customization identification, yes? Or does anything not work?

**Comment by Ottermandias** [comment]
Added the enums, anything missing or not working?

**Comment by Sevii77** [comment]
Think the issue was related due to the mod being outdated, updated it and it works fine now. Assumed it would work fine since viera uses the hyur model (i thought atleast). Closing
