### ISSUE TITLE
Not loading mods after entering gpose

### ISSUE THREAD

**Issue by fatpeoplemagic** [xivdev/Penumbra#82]
Penumbra loaded everything fine outside of gpose. I opened gpose and nothing remained modded anymore, just vanilla. While in gpose, I opened Penumbra and enabled/disabled mods multiple times to try and get it to redraw my character and nothing happened. I also tried /penumbra reload just in case it was that. No change. After exiting gpose, all mods reappeared on the character.

**Comment by Ottermandias** [comment]
Should be fixed.
