### ISSUE TITLE
Character Collections not applying in cutscenes

### ISSUE THREAD

**Issue by Lambadelta** [xivdev/Penumbra#83]
Sorry if I'm blind, but I've been unable to figure out how to get mods as part of a character collection to apply during a cutscene, or in the try on window without having the mods set as part of the default collection.

Is there a way to do this, or will this be eventually added later on.

My current setup is just UI mods on default, and gear/hair mods being on my character collection.

**Comment by Ottermandias** [comment]
The Try-On window can not be supported because the actor in it is not redrawable and has no name.
Redrawing in cutscenes deletes animations, so you do not want that except if you want your character to be T-posing through the cutscene.

**Comment by Lambadelta** [comment]
Ah so if I want to have mods appear in cutscenes/try-on they can't be in collections. That is a shame, but atleast I know now.

Is there an easy way to change what item a mod is attached to in penumbra, or is that something I should do in textools?

**Comment by Ottermandias** [comment]
No easy way for the moment, use TT if necessary.
