### ISSUE TITLE
Mods not working since Dalamud plugins update

### ISSUE THREAD

**Issue by FiraliaDev** [xivdev/Penumbra#88]
I cannot for the life of me work out what the problem is here.
My laptop was in repairs for a couple months (Sept-Nov), and when I came back (around 2 weeks before 6.0), I was greeted with that massive Dalamud plugins update, and mods in Penumbra stopped working.

Essentially what happens is, all my mods are there. Penumbra loads fine, and so do all my mod files, but when I actually enable a mod, nothing happens. It doesn't display at all.

I'm guessing it's a Dalamud problem, but I can't figure out what would be causing it. I've moved Penumbra from `devPlugins` to a custom repository. Tried deleting all the penumbra files and doing a complete reinstall of it as well, but still nothing.

**Comment by Ottermandias** [comment]
Please make screenshots of your Settings tab and your Collections tab.

**Comment by FiraliaDev** [comment]
![image](https://user-images.githubusercontent.com/70761661/146234093-78614a60-3c88-4b0c-941c-714a40fec20f.png)
![image](https://user-images.githubusercontent.com/70761661/146234118-030760b3-bd98-47f9-9e87-14a06d10e244.png)

**Comment by Ottermandias** [comment]
Looks fine. You could try setting the Default Collection to None and then back to Default.
What version are you on? I hope you're using the repo? If not, please do.
Also make sure there are no remnants of Penumbra left in your DevPlugins folder, then.

**Comment by FiraliaDev** [comment]
I'm on version 0.4.6.5, and yes, I'm using the repo. No remnants left in devPlugins.
Messing with collection settings doesn't seem to do anything.

**Comment by Ottermandias** [comment]
What mods are you trying to enable? Some/Most Character Customization mods won't reload on redraws and require a full restart, but since you have reinstalled I assume that's not the issue? 
Your path also has no weird symbols in it... do Files appear in your Effective Changes tab when you enable mods, or does it stay empty?

**Comment by lmcintyre** [comment]
Just for the record, I tried to assist a friend in setting up Material UI 4k 6.0.0 preliminary via Penumbra last night and had this same issue with a fresh Penumbra install. The mod works perfect for me - I have never had an issue. However, for him, Penumbra did nothing. The log contained the info about extraction process of the ttmp2, and after that there was nothing from Penumbra. Accessing the aesthetician to reload UI did not work (like it does for me), and starting the game over again did nothing either. I have no clue how this is happening.

**Comment by Ottermandias** [comment]
Did I fuck up initial load of collections again? :/
Can Firalia and your friend enter `/penumbra debug`  and look in the debug tab what the collection state is like?

**Comment by lmcintyre** [comment]
I can get him to do that later. On the other hand, *my* collection.json file has not been modified since October (I have installed mods since then) and my friend's Penumba folder does not have a collection.json file at all.

**Comment by Ottermandias** [comment]
They're not used anymore since collections were introduced, the new files are in the `pluginConfigs/Penumbra/collections` folder.

**Comment by lmcintyre** [comment]
![image](https://user-images.githubusercontent.com/6005409/146260527-6fb4c17c-bfb6-48b0-b617-9980d9ddf3a4.png)
This is the debug tab, collection info. His path does not have special characters.

**Comment by FiraliaDev** [comment]
Here's mine. To answer your question from earlier, all my mods that I've tried using are just outfits, hair, face makeup, things like that. Nothing appears in effective changes.
![image](https://user-images.githubusercontent.com/70761661/146313617-045b0a1b-1246-4795-82d9-5f2378dc2c3a.png)

**Comment by Ottermandias** [comment]
Your temp path is NULL. Try changing your base path to something else and resetting it to your original path.
If that doesn't work, try manually setting the temp path to something (possibly to your base path or to the empty string).
That's definitely your problem, I don't know how you got to it though.

**Comment by FiraliaDev** [comment]
Manually setting a temp path seems to have worked. Thank you!
