### ISSUE TITLE
Collection not working after reaper's enshroud ends

### ISSUE THREAD

**Issue by akira0245** [xivdev/Penumbra#89]
I use a collection named with my character's name and set default collection to none to only apply mods on myself
![image](https://user-images.githubusercontent.com/33274390/146312325-f36c9c31-cdda-4f3c-80f0-528b2f727b01.png)
but after the Enshrouded effect ends, all modded equipment are drawn as their original appearance (maybe the default collection appearance)

**Comment by Ottermandias** [comment]
Yeah, reaper shroud does neither change your watched state nor reload you, so automatic redrawing does not do anything here. You can manually redraw afterwards, of course.

**Comment by akira0245** [comment]
Use forced collection could solve this issue temporarily, still looking forward to find a perfect solution. Thank you!
