### ISSUE TITLE
Character collections not working. 

### ISSUE THREAD

**Issue by SkuddleButt** [xivdev/Penumbra#96]
It seems my collections aren't working quite right, I reset my settings and reinstalled penumbra and they still won't. The only way for a collection to work for me currently is to either have it set as default or forced. Any other character collections mods aren't detected and don't show up in effective changed. But they will if that collection is set to as default or forced. I'm not sure if its something i'm missing or I've encountered a bug, it was working the day before.

**Comment by Ottermandias** [comment]
It was definitely not working like that the day before. You will never have mods inside a character collection be displayed in Effective Changes.

**Comment by SkuddleButt** [comment]
I thought it did, I'm definitely wrong in that case. I don't know why then that character collections aren't applying until they are set as default.

**Comment by SkuddleButt** [comment]
Uninstalling the plugin, clearing out mods, relaunching the game and reinstalling the plugin seems to have fixed the issue and character specific collections seem to be working again.

**Comment by Ottermandias** [comment]
Weird, but great!
